/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface AnswerDto {
  id?: number
  /** @nullable */
  traLoi?: string | null
}
