/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { OrganizationMobileDto } from './organizationMobileDto'

/**
 * Represents a standard API response for single-item operations (Get, Create, Update, Delete).
 */
export interface ApiResultOfOrganizationMobileDto {
  /** Indicates whether the request was successful. */
  success?: boolean
  data?: OrganizationMobileDto
  /**
   * An optional message, providing more details about the result.
   * @nullable
   */
  message?: string | null
}
