/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

/**
 * A non-generic version of ApiResult, typically used for operations
where no data payload is returned (e.g., Delete, Update).
 */
export interface ApiResult {
  /** Indicates whether the request was successful. */
  success?: boolean
  /**
   * An optional message, providing more details about the result.
   * @nullable
   */
  message?: string | null
}
