/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { UserDto } from './userDto'

/**
 * Represents a standard API response for single-item operations (Get, Create, Update, Delete).
 */
export interface ApiResultOfUserDto {
  /** Indicates whether the request was successful. */
  success?: boolean
  data?: UserDto
  /**
   * An optional message, providing more details about the result.
   * @nullable
   */
  message?: string | null
}
