/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { HotlineDto } from './hotlineDto'

/**
 * Represents a standard API response for single-item operations (Get, Create, Update, Delete).
 */
export interface ApiResultOfListHotlineDto {
  /** Indicates whether the request was successful. */
  success?: boolean
  /**
   * The data payload. Can be null for operations like Delete.
   * @nullable
   */
  data?: HotlineDto[] | null
  /**
   * An optional message, providing more details about the result.
   * @nullable
   */
  message?: string | null
}
