/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

/**
 * Represents a standard API response for single-item operations (Get, Create, Update, Delete).
 */
export interface ApiResultOfInt32 {
  /** Indicates whether the request was successful. */
  success?: boolean
  /** The data payload. Can be null for operations like Delete. */
  data?: number
  /**
   * An optional message, providing more details about the result.
   * @nullable
   */
  message?: string | null
}
