/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

/**
 * The data payload. Can be null for operations like Delete.
 * @nullable
 */
export type ApiResultOfObjectData = unknown | null
