/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface ApproveFeedbackResponseDto {
  responseId: number
  isApproved?: boolean
  /**
   * @maxLength 500
   * @nullable
   */
  approvalNote?: string | null
}
