/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface ArticleProcessingHistoryDto {
  id?: number
  publicId?: string
  fromStatusId?: number
  /** @nullable */
  fromStatusName?: string | null
  /** @nullable */
  fromStatusCode?: string | null
  toStatusId?: number
  /** @nullable */
  toStatusName?: string | null
  /** @nullable */
  toStatusCode?: string | null
  /** @nullable */
  action?: string | null
  /** @nullable */
  actorUserPublicId?: string | null
  /** @nullable */
  actorName?: string | null
  /** @nullable */
  note?: string | null
  createdAt?: string
}
