/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface AssignFeedbackDto {
  feedbackPublicId: string
  departmentPublicId: string
  toStatusId: number
  /**
   * @maxLength 1000
   * @nullable
   */
  processingNote?: string | null
}
