/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface BannerMobileDto {
  publicId?: string
  /** @nullable */
  title: string | null
  /** @nullable */
  imageUrl: string | null
  /** @nullable */
  position: string | null
  /** @nullable */
  bannerType: string | null
  /** @nullable */
  nativeParams?: string | null
  /** @nullable */
  webLink?: string | null
  thuTu?: number
}
