/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface CreateHomestayCommand {
  /** @nullable */
  name: string | null
  /** @nullable */
  address: string | null
  /** @nullable */
  description: string | null
  /** @nullable */
  phoneNumber: string | null
  /** @nullable */
  website?: string | null
  /** @nullable */
  linkVitri?: string | null
  averagePrice?: number
  /** @nullable */
  latitude?: number | null
  /** @nullable */
  longitude?: number | null
  /** @nullable */
  thuTu?: number | null
  /** @nullable */
  imagePublicIds?: string[] | null
}
