/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface CreateFeedbackMobileDto {
  /**
   * @minLength 1
   * @maxLength 500
   */
  title: string
  /** @minLength 1 */
  content: string
  /**
   * @minLength 1
   * @maxLength 200
   */
  fullName: string
  /**
   * @maxLength 20
   * @nullable
   */
  phoneNumber?: string | null
  /**
   * @maxLength 500
   * @nullable
   */
  location?: string | null
  isPublic?: boolean
  /** @nullable */
  attachmentPublicIds?: string[] | null
}
