/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface CreateIconCommand {
  /** @nullable */
  iconCategoryPublicId?: string | null
  /** @nullable */
  iconGroupPublicId?: string | null
  /** @nullable */
  name: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  iconImageUrl?: string | null
  /** @nullable */
  imagePublicId?: string | null
  /** @nullable */
  iconType: string | null
  /** @nullable */
  screenParams?: string | null
  /** @nullable */
  webLink?: string | null
  /** @nullable */
  linkAndroid?: string | null
  /** @nullable */
  linkIOS?: string | null
  displayOrder?: number
  /** @nullable */
  thuTu?: number | null
}
