/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface CreateHotelCommand {
  /** @nullable */
  name: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  address?: string | null
  /** @nullable */
  starRating?: number | null
  /** @nullable */
  phoneNumber?: string | null
  /** @nullable */
  email?: string | null
  /** @nullable */
  website?: string | null
  /** @nullable */
  operatingHours?: string | null
  /** @nullable */
  latitude?: number | null
  /** @nullable */
  longitude?: number | null
  /** @nullable */
  vR360Link?: string | null
  /** @nullable */
  priceFrom?: number | null
  /** @nullable */
  priceFromCurrency?: string | null
  /** @nullable */
  thuTu?: number | null
  /** @nullable */
  imagePublicIds?: string[] | null
}
