/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface DepartmentUserDto {
  userPublicId?: string
  /** @nullable */
  userName: string | null
  /** @nullable */
  fullName: string | null
  /** @nullable */
  email: string | null
  isActive?: boolean
  createdAt?: string
}
