/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface EssayResponseByUserDto {
  idUser?: number
  surveyId?: number
  essayQuestionId?: number
  /** @nullable */
  cauHoiTuLuan?: string | null
  /** @nullable */
  content?: string | null
  createdAt?: string
}
