/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface FeedbackStatusDto {
  publicId: string
  /** @nullable */
  code: string | null
  /** @nullable */
  name: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  color?: string | null
  sortOrder?: number
  isActive?: boolean
  createdAt?: string
  updatedAt?: string
}
