/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { FeedbackResponseAttachmentMobileDto } from './feedbackResponseAttachmentMobileDto'

export interface FeedbackResponseMobileDto {
  id?: number
  publicId?: string
  /** @nullable */
  responseContent: string | null
  /** @nullable */
  isApproved?: boolean | null
  /** @nullable */
  approvedAt?: string | null
  createdAt?: string
  updatedAt?: string
  /** @nullable */
  attachments?: FeedbackResponseAttachmentMobileDto[] | null
}
