/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface FeedbackAttachmentMobileDto {
  filePublicId: string
  /**
   * @minLength 1
   * @maxLength 500
   */
  fileName: string
  fileSize?: number
  /**
   * @maxLength 10
   * @nullable
   */
  fileType?: string | null
  sortOrder?: number
  /** @nullable */
  fileUrl?: string | null
}
