/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface FileInfoDto {
  publicId?: string
  /** @nullable */
  fileName: string | null
  fileSize?: number
  /** @nullable */
  contentType: string | null
  /** @nullable */
  description?: string | null
  ordinal?: number
  /** @nullable */
  url?: string | null
  uploadedAt?: string
  /** @nullable */
  uploadedById?: number | null
  /** @nullable */
  uploadedByName?: string | null
}
