/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export type GetApiZaloMiniAppMobileFeedbackHistoryParams = {
  phoneNumber?: string
  current?: number
  pageSize?: number
  title?: string
  currentStatusId?: number
  createdFrom?: string
  createdTo?: string
}
