/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export type GetApiUsersParams = {
  Current?: number
  PageSize?: number
  FullName?: string
  Email?: string
  IsActive?: boolean
}
