/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export type GetApiZaloMiniAppAdminFeedbackTrackingParams = {
  current?: number
  pageSize?: number
  title?: string
  phoneNumber?: string
  currentStatusId?: number
  currentStatusCode?: string
  assignedDepartmentPublicId?: string
  isActive?: boolean
  createdFrom?: string
  createdTo?: string
}
