/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export type GetApiZaloMiniAppAdminHomestaysParams = {
  Current?: number
  PageSize?: number
  Name?: string
  Address?: string
  PhoneNumber?: string
  MinPrice?: number
  MaxPrice?: number
  IsActive?: boolean
}
