/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export type GetApiZaloMiniAppAdminServicesIconsParams = {
  Current?: number
  PageSize?: number
  Name?: string
  IconType?: string
  IconCategoryPublicId?: string
  IconGroupPublicId?: string
  IsActive?: boolean
}
