/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export type GetApiAdminTintucParams = {
  Current?: number
  PageSize?: number
  Keyword?: string
  CategoryId?: number
  CurrentStatusId?: number
  IsPublic?: boolean
  IsActive?: boolean
  CreatedFrom?: string
  CreatedTo?: string
}
