/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export type GetApiZaloMiniAppMobileRestaurantsParams = {
  Current?: number
  PageSize?: number
  Name?: string
  IsActive?: boolean
  Category?: string
  Address?: string
  PhoneNumber?: string
  MinPrice?: number
  MaxPrice?: number
  PriceRange?: string
}
