/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export type GetApiZaloMiniAppAdminFeedbackStatusesParams = {
  current?: number
  pageSize?: number
  name?: string
  code?: string
  isActive?: boolean
}
