/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export type GetApiZaloMiniAppMobileOcopProductsByEnterpriseEnterprisePublicIdParams = {
  EnterprisePublicId?: string
  Current?: number
  PageSize?: number
  Name?: string
  MinPrice?: number
  MaxPrice?: number
}
