/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export type GetApiZaloMiniAppMobileFeedbackPublicParams = {
  current?: number
  pageSize?: number
  title?: string
  fullName?: string
  location?: string
  createdFrom?: string
  createdTo?: string
}
