/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export type GetApiZaloMiniAppMobileHotelsParams = {
  Current?: number
  PageSize?: number
  Name?: string
  IsActive?: boolean
  StarRating?: number
  Address?: string
  PhoneNumber?: string
  Email?: string
  MinPrice?: number
  MaxPrice?: number
  PriceFromCurrency?: string
}
