/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export type GetApiZaloMiniAppAdminKhaosatParams = {
  Current?: number
  PageSize?: number
  TenKhaoSat?: string
  From?: string
  To?: string
  IsActive?: boolean
}
