/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export type GetApiZaloMiniAppAdminServicesSupportGroupsParams = {
  Current?: number
  PageSize?: number
  GroupName?: string
  GroupType?: string
  CategoryPublicId?: string
}
