/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface GetPhoneNumberRequestDto {
  /**
   * Token từ getPhoneNumber API của Zalo SDK
   * @nullable
   */
  token: string | null
  /**
   * Access token của user
   * @nullable
   */
  accessToken: string | null
}
