/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface GetPhoneNumberResponseDto {
  /**
   * Số điện thoại ở định dạng quốc tế (84xxxxxxxxx)
   * @nullable
   */
  phoneNumber: string | null
  /**
   * Số điện thoại đã được định dạng để hiển thị (0xxxxxxxxx)
   * @nullable
   */
  displayPhoneNumber?: string | null
}
