/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface HotlineMobileDto {
  publicId?: string
  /** @nullable */
  phoneNumber: string | null
  /** @nullable */
  contactName: string | null
  /** @nullable */
  description?: string | null
  thuTu?: number
}
