/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { HotlineMobileDto } from './hotlineMobileDto'

export interface HotlineCategoryMobileDto {
  publicId?: string
  /** @nullable */
  name: string | null
  /** @nullable */
  description?: string | null
  thuTu?: number
  /** @nullable */
  hotlines?: HotlineMobileDto[] | null
}
