/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { IconCategoryMobileDto } from './iconCategoryMobileDto'

export interface IconConfigDto {
  /** @nullable */
  categories?: IconCategoryMobileDto[] | null
}
