/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { IconGroupMobileDto } from './iconGroupMobileDto'
import type { IconMobileDto } from './iconMobileDto'

export interface IconCategoryMobileDto {
  publicId?: string
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string
  displayOrder?: number
  isActive?: boolean
  /** @nullable */
  groups?: IconGroupMobileDto[] | null
  /** @nullable */
  icons?: IconMobileDto[] | null
}
