/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface IconMobileDto {
  publicId?: string
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string
  /**
   * @minLength 1
   * @maxLength 500
   */
  iconImageUrl: string
  /**
   * @minLength 1
   * @maxLength 20
   */
  iconType: string
  /**
   * @maxLength 1000
   * @nullable
   */
  screenParams?: string | null
  /**
   * @maxLength 500
   * @nullable
   */
  webLink?: string | null
  /** @nullable */
  linkAndroid?: string | null
  /** @nullable */
  linkIOS?: string | null
  displayOrder?: number
  /** @nullable */
  categoryName?: string | null
  /** @nullable */
  groupName?: string | null
}
