/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { IconMobileDto } from './iconMobileDto'

export interface IconGroupMobileDto {
  publicId?: string
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string
  displayOrder?: number
  isActive?: boolean
  /**
   * @maxLength 500
   * @nullable
   */
  imageUrl?: string | null
  /** @nullable */
  imagePublicId?: string | null
  /** @nullable */
  icons?: IconMobileDto[] | null
}
