/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { KhaoSatMobileControllerEssayItem } from './khaoSatMobileControllerEssayItem'

export interface KhaoSatMobileControllerSubmitEssayRequest {
  surveyId?: number
  idUser?: number
  /** @nullable */
  items?: KhaoSatMobileControllerEssayItem[] | null
}
