/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface OtherOpinionDto {
  id?: number
  /** @nullable */
  userID?: string | null
  /** @nullable */
  yKienKhac?: string | null
  createdAt?: string
}
