/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface PaymentTransactionDto {
  publicId?: string
  bookingOrderId?: number
  amount?: number
  /** @nullable */
  currency?: string | null
  /** @nullable */
  paymentMethod?: string | null
  /** @nullable */
  status?: string | null
  /** @nullable */
  gatewayTransactionId?: string | null
  /** @nullable */
  gatewayResponseCode?: string | null
  /** @nullable */
  gatewayMessage?: string | null
  createdAt?: string
  updatedAt?: string
}
