/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface ProfileDto {
  publicId?: string
  /** @nullable */
  address?: string | null
  /** @nullable */
  workplace?: string | null
  /** @nullable */
  jobTitle?: string | null
  /** @nullable */
  position?: string | null
  /** @nullable */
  gender?: boolean | null
  /** @nullable */
  dateOfBirth?: string | null
  createdAt?: string
  updatedAt?: string
}
