/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface ResponseKhaoSatCommand {
  surveyId?: number
  idUser?: number
  /** @nullable */
  cauHoi: number[] | null
  /** @nullable */
  dapAn: number[] | null
  /** @nullable */
  hoTen?: string | null
  /** @nullable */
  diaChi?: string | null
}
