/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface SupportGroupMobileDto {
  publicId?: string
  /** @nullable */
  groupName: string | null
  /** @nullable */
  groupLink: string | null
  /** @nullable */
  groupType: string | null
  /** @nullable */
  description?: string | null
}
