/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface TinTucUpdateArticleAttachmentInput {
  filePublicId?: string
  /** @nullable */
  fileName: string | null
  fileSize?: number
  /** @nullable */
  fileType?: string | null
  sortOrder?: number
}
