/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { TinTucCreateArticleAttachmentInput } from './tinTucCreateArticleAttachmentInput'

export interface TinTucCreateArticleCommand {
  /** @nullable */
  title: string | null
  /** @nullable */
  summary?: string | null
  /** @nullable */
  content: string | null
  /** @nullable */
  thumbnailUrl?: string | null
  categoryId?: number
  /** @nullable */
  tags?: string | null
  /** @nullable */
  authorName?: string | null
  /** @nullable */
  attachments?: TinTucCreateArticleAttachmentInput[] | null
}
