/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface TotalUserDto {
  id?: number
  /** @nullable */
  userId: string | null
  /** @nullable */
  username: string | null
  /** @nullable */
  avatar?: string | null
  /** @nullable */
  phanQuyen?: string | null
  /** @nullable */
  phoneNumber?: string | null
}
