/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface TourImageDto {
  /** @nullable */
  publicId?: string | null
  /** @nullable */
  imageUrl?: string | null
  /** @nullable */
  imagePublicId?: string | null
  displayOrder?: number
  isPrimary?: boolean
  /** @nullable */
  caption?: string | null
}
