/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface UpdateIconGroupCommand {
  publicId: string
  iconCategoryPublicId: string
  /** @nullable */
  name: string | null
  /** @nullable */
  description?: string | null
  displayOrder?: number
  isActive?: boolean
  /** @nullable */
  thuTu?: number | null
  /** @nullable */
  imagePublicId?: string | null
}
