/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface UpdateOcopProductCommand {
  publicId: string
  /** @nullable */
  name: string | null
  /** @nullable */
  description?: string | null
  categoryPublicId?: string
  enterprisePublicId?: string
  /** @nullable */
  referencePrice?: number | null
  /** @nullable */
  promotionalPrice?: number | null
  /** @nullable */
  contactPhone?: string | null
  /** @nullable */
  contactAddress?: string | null
  /** @nullable */
  latitude?: number | null
  /** @nullable */
  longitude?: number | null
  isActive?: boolean
  /** @nullable */
  imagePublicIds?: string[] | null
}
