/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface UpdateFeedbackDto {
  publicId: string
  /**
   * @maxLength 500
   * @nullable
   */
  title?: string | null
  /** @nullable */
  content?: string | null
  /**
   * @maxLength 200
   * @nullable
   */
  fullName?: string | null
  /**
   * @maxLength 20
   * @nullable
   */
  phoneNumber?: string | null
  /**
   * @maxLength 500
   * @nullable
   */
  location?: string | null
  /** @nullable */
  isPublic?: boolean | null
  /** @nullable */
  currentStatusId?: number | null
  /** @nullable */
  assignedDepartmentPublicId?: string | null
}
