/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface UpdateRoleCommand {
  publicId?: string
  /** @nullable */
  name: string | null
  /** @nullable */
  code: string | null
  /** @nullable */
  description?: string | null
}
