/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserRolesCommand {
  /** @nullable */
  publicId?: string | null
  /** @nullable */
  roleCodes?: string[] | null
}
