/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

/**
 * DTO trả về cho mỗi file được upload, tương thích với Ant Design Upload component.
 */
export interface UploadFileResponseDto {
  /** ID duy nhất cho file ở phía client (sử dụng PublicId của file). */
  uid?: string
  /** PublicId của file trong database, dùng để liên kết sau này. */
  publicId?: string
  /**
   * Tên file gốc.
   * @nullable
   */
  name: string | null
  /**
   * Trạng thái upload, mặc định là "done" vì API chỉ trả về khi đã hoàn tất.
   * @nullable
   */
  status?: string | null
  /**
   * URL để truy cập/tải file.
   * @nullable
   */
  url: string | null
}
