/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { ProfileDto } from './profileDto'

export interface UserProfileDto {
  /** @nullable */
  userName: string | null
  /** @nullable */
  email: string | null
  /** @nullable */
  fullName: string | null
  isActive?: boolean
  userCreatedAt?: string
  profile?: ProfileDto
}
