/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */

export interface UserDepartmentDto {
  userPublicId?: string
  /** @nullable */
  userName: string | null
  /** @nullable */
  userFullName: string | null
  departmentPublicId?: string
  /** @nullable */
  departmentCode: string | null
  /** @nullable */
  departmentName: string | null
  organizationPublicId?: string
  /** @nullable */
  organizationName: string | null
}
