/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { ApiResultOfListBannerMobileDto } from '../models'

import { customRequest } from '../request'

export const getBannersMobile = () => {
  const getApiZaloMiniAppMobileBanners = () => {
    return customRequest<ApiResultOfListBannerMobileDto>({
      url: `/api/zalo-mini-app/mobile/banners`,
      method: 'GET',
    })
  }
  return { getApiZaloMiniAppMobileBanners }
}
export type GetApiZaloMiniAppMobileBannersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getBannersMobile>['getApiZaloMiniAppMobileBanners']>>
>
