/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfBannerDto,
  CreateBannerCommand,
  DeleteBannerCommand,
  GetApiZaloMiniAppAdminBannersParams,
  PagedResultOfBannerDto,
  UpdateBannerCommand,
} from '../models'

import { customRequest } from '../request'

export const getBannersAdmin = () => {
  const postApiZaloMiniAppAdminBannersCreate = (createBannerCommand: CreateBannerCommand) => {
    return customRequest<ApiResultOfBannerDto>({
      url: `/api/zalo-mini-app/admin/banners/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createBannerCommand,
    })
  }
  const getApiZaloMiniAppAdminBannersPublicId = (publicId: string) => {
    return customRequest<ApiResultOfBannerDto>({
      url: `/api/zalo-mini-app/admin/banners/${publicId}`,
      method: 'GET',
    })
  }
  const getApiZaloMiniAppAdminBanners = (params?: GetApiZaloMiniAppAdminBannersParams) => {
    return customRequest<PagedResultOfBannerDto>({
      url: `/api/zalo-mini-app/admin/banners`,
      method: 'GET',
      params,
    })
  }
  const postApiZaloMiniAppAdminBannersUpdate = (updateBannerCommand: UpdateBannerCommand) => {
    return customRequest<ApiResultOfBannerDto>({
      url: `/api/zalo-mini-app/admin/banners/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateBannerCommand,
    })
  }
  const postApiZaloMiniAppAdminBannersDelete = (deleteBannerCommand: DeleteBannerCommand) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/banners/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteBannerCommand,
    })
  }
  return {
    postApiZaloMiniAppAdminBannersCreate,
    getApiZaloMiniAppAdminBannersPublicId,
    getApiZaloMiniAppAdminBanners,
    postApiZaloMiniAppAdminBannersUpdate,
    postApiZaloMiniAppAdminBannersDelete,
  }
}
export type PostApiZaloMiniAppAdminBannersCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getBannersAdmin>['postApiZaloMiniAppAdminBannersCreate']>>
>
export type GetApiZaloMiniAppAdminBannersPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getBannersAdmin>['getApiZaloMiniAppAdminBannersPublicId']>>
>
export type GetApiZaloMiniAppAdminBannersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getBannersAdmin>['getApiZaloMiniAppAdminBanners']>>
>
export type PostApiZaloMiniAppAdminBannersUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getBannersAdmin>['postApiZaloMiniAppAdminBannersUpdate']>>
>
export type PostApiZaloMiniAppAdminBannersDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getBannersAdmin>['postApiZaloMiniAppAdminBannersDelete']>>
>
