/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfDepartmentDto,
  ApiResultOfDepartmentWithOrganizationDto,
  ApiResultOfOrganizationDto,
  ApiResultOfOrganizationWithDepartmentsDto,
  ApiResultOfUserDepartmentDto,
  AssignUserToDepartmentCommand,
  CreateDepartmentCommand,
  CreateOrganizationCommand,
  DeleteDepartmentCommand,
  DeleteOrganizationCommand,
  GetApiAdminCommonDepartmentsDepartmentPublicIdUsersParams,
  GetApiAdminCommonDepartmentsParams,
  GetApiAdminCommonOrganizationsParams,
  PagedResultOfDepartmentDto,
  PagedResultOfDepartmentUserDto,
  PagedResultOfOrganizationDto,
  RemoveUserFromDepartmentCommand,
  UpdateDepartmentCommand,
  UpdateOrganizationCommand,
} from '../models'

import { customRequest } from '../request'

export const getCommonAdmin = () => {
  const getApiAdminCommonOrganizations = (params?: GetApiAdminCommonOrganizationsParams) => {
    return customRequest<PagedResultOfOrganizationDto>({
      url: `/api/admin/common/organizations`,
      method: 'GET',
      params,
    })
  }
  const getApiAdminCommonOrganizationsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfOrganizationWithDepartmentsDto>({
      url: `/api/admin/common/organizations/${publicId}`,
      method: 'GET',
    })
  }
  const postApiAdminCommonOrganizationsCreate = (
    createOrganizationCommand: CreateOrganizationCommand
  ) => {
    return customRequest<ApiResultOfOrganizationDto>({
      url: `/api/admin/common/organizations/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createOrganizationCommand,
    })
  }
  const postApiAdminCommonOrganizationsUpdate = (
    updateOrganizationCommand: UpdateOrganizationCommand
  ) => {
    return customRequest<ApiResultOfOrganizationWithDepartmentsDto>({
      url: `/api/admin/common/organizations/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateOrganizationCommand,
    })
  }
  const getApiAdminCommonDepartments = (params?: GetApiAdminCommonDepartmentsParams) => {
    return customRequest<PagedResultOfDepartmentDto>({
      url: `/api/admin/common/departments`,
      method: 'GET',
      params,
    })
  }
  const getApiAdminCommonDepartmentsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfDepartmentWithOrganizationDto>({
      url: `/api/admin/common/departments/${publicId}`,
      method: 'GET',
    })
  }
  const postApiAdminCommonDepartmentsCreate = (
    createDepartmentCommand: CreateDepartmentCommand
  ) => {
    return customRequest<ApiResultOfDepartmentDto>({
      url: `/api/admin/common/departments/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createDepartmentCommand,
    })
  }
  const postApiAdminCommonDepartmentsUpdate = (
    updateDepartmentCommand: UpdateDepartmentCommand
  ) => {
    return customRequest<ApiResultOfDepartmentDto>({
      url: `/api/admin/common/departments/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateDepartmentCommand,
    })
  }
  const postApiAdminCommonOrganizationsDelete = (
    deleteOrganizationCommand: DeleteOrganizationCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/admin/common/organizations/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteOrganizationCommand,
    })
  }
  const postApiAdminCommonDepartmentsDelete = (
    deleteDepartmentCommand: DeleteDepartmentCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/admin/common/departments/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteDepartmentCommand,
    })
  }
  const postApiAdminCommonDepartmentsUsersAssign = (
    assignUserToDepartmentCommand: AssignUserToDepartmentCommand
  ) => {
    return customRequest<ApiResultOfUserDepartmentDto>({
      url: `/api/admin/common/departments/users/assign`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: assignUserToDepartmentCommand,
    })
  }
  const postApiAdminCommonDepartmentsUsersRemove = (
    removeUserFromDepartmentCommand: RemoveUserFromDepartmentCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/admin/common/departments/users/remove`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: removeUserFromDepartmentCommand,
    })
  }
  const getApiAdminCommonDepartmentsDepartmentPublicIdUsers = (
    departmentPublicId: string,
    params: GetApiAdminCommonDepartmentsDepartmentPublicIdUsersParams
  ) => {
    return customRequest<PagedResultOfDepartmentUserDto>({
      url: `/api/admin/common/departments/${departmentPublicId}/users`,
      method: 'GET',
      params,
    })
  }
  return {
    getApiAdminCommonOrganizations,
    getApiAdminCommonOrganizationsPublicId,
    postApiAdminCommonOrganizationsCreate,
    postApiAdminCommonOrganizationsUpdate,
    getApiAdminCommonDepartments,
    getApiAdminCommonDepartmentsPublicId,
    postApiAdminCommonDepartmentsCreate,
    postApiAdminCommonDepartmentsUpdate,
    postApiAdminCommonOrganizationsDelete,
    postApiAdminCommonDepartmentsDelete,
    postApiAdminCommonDepartmentsUsersAssign,
    postApiAdminCommonDepartmentsUsersRemove,
    getApiAdminCommonDepartmentsDepartmentPublicIdUsers,
  }
}
export type GetApiAdminCommonOrganizationsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonAdmin>['getApiAdminCommonOrganizations']>>
>
export type GetApiAdminCommonOrganizationsPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonAdmin>['getApiAdminCommonOrganizationsPublicId']>>
>
export type PostApiAdminCommonOrganizationsCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonAdmin>['postApiAdminCommonOrganizationsCreate']>>
>
export type PostApiAdminCommonOrganizationsUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonAdmin>['postApiAdminCommonOrganizationsUpdate']>>
>
export type GetApiAdminCommonDepartmentsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonAdmin>['getApiAdminCommonDepartments']>>
>
export type GetApiAdminCommonDepartmentsPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonAdmin>['getApiAdminCommonDepartmentsPublicId']>>
>
export type PostApiAdminCommonDepartmentsCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonAdmin>['postApiAdminCommonDepartmentsCreate']>>
>
export type PostApiAdminCommonDepartmentsUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonAdmin>['postApiAdminCommonDepartmentsUpdate']>>
>
export type PostApiAdminCommonOrganizationsDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonAdmin>['postApiAdminCommonOrganizationsDelete']>>
>
export type PostApiAdminCommonDepartmentsDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonAdmin>['postApiAdminCommonDepartmentsDelete']>>
>
export type PostApiAdminCommonDepartmentsUsersAssignResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonAdmin>['postApiAdminCommonDepartmentsUsersAssign']>>
>
export type PostApiAdminCommonDepartmentsUsersRemoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonAdmin>['postApiAdminCommonDepartmentsUsersRemove']>>
>
export type GetApiAdminCommonDepartmentsDepartmentPublicIdUsersResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCommonAdmin>['getApiAdminCommonDepartmentsDepartmentPublicIdUsers']
    >
  >
>
