/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfDepartmentMobileDto,
  ApiResultOfOrganizationMobileDto,
  GetApiMobileCommonDepartmentsParams,
  GetApiMobileCommonOrganizationsParams,
  PagedResultOfDepartmentMobileDto,
  PagedResultOfOrganizationMobileDto,
} from '../models'

import { customRequest } from '../request'

export const getCommonMobile = () => {
  const getApiMobileCommonOrganizations = (params?: GetApiMobileCommonOrganizationsParams) => {
    return customRequest<PagedResultOfOrganizationMobileDto>({
      url: `/api/mobile/common/organizations`,
      method: 'GET',
      params,
    })
  }
  const getApiMobileCommonOrganizationsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfOrganizationMobileDto>({
      url: `/api/mobile/common/organizations/${publicId}`,
      method: 'GET',
    })
  }
  const getApiMobileCommonDepartments = (params?: GetApiMobileCommonDepartmentsParams) => {
    return customRequest<PagedResultOfDepartmentMobileDto>({
      url: `/api/mobile/common/departments`,
      method: 'GET',
      params,
    })
  }
  const getApiMobileCommonDepartmentsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfDepartmentMobileDto>({
      url: `/api/mobile/common/departments/${publicId}`,
      method: 'GET',
    })
  }
  return {
    getApiMobileCommonOrganizations,
    getApiMobileCommonOrganizationsPublicId,
    getApiMobileCommonDepartments,
    getApiMobileCommonDepartmentsPublicId,
  }
}
export type GetApiMobileCommonOrganizationsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonMobile>['getApiMobileCommonOrganizations']>>
>
export type GetApiMobileCommonOrganizationsPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonMobile>['getApiMobileCommonOrganizationsPublicId']>>
>
export type GetApiMobileCommonDepartmentsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonMobile>['getApiMobileCommonDepartments']>>
>
export type GetApiMobileCommonDepartmentsPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCommonMobile>['getApiMobileCommonDepartmentsPublicId']>>
>
