/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { ApiResultOfDashboardStatsDto } from '../models'

import { customRequest } from '../request'

export const getDashboard = () => {
  const getApiDashboardStats = () => {
    return customRequest<ApiResultOfDashboardStatsDto>({
      url: `/api/dashboard/stats`,
      method: 'GET',
    })
  }
  return { getApiDashboardStats }
}
export type GetApiDashboardStatsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDashboard>['getApiDashboardStats']>>
>
