/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { ApiResultOfObject } from '../models'

import { customRequest } from '../request'

export const getDiagnostics = () => {
  const getApiDiagnosticsDbCheck = () => {
    return customRequest<ApiResultOfObject>({ url: `/api/diagnostics/db-check`, method: 'GET' })
  }
  return { getApiDiagnosticsDbCheck }
}
export type GetApiDiagnosticsDbCheckResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDiagnostics>['getApiDiagnosticsDbCheck']>>
>
