/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfFeedbackTrackingDto,
  GetApiZaloMiniAppAdminFeedbackTrackingParams,
  PagedResultOfFeedbackTrackingDto,
} from '../models'

import { customRequest } from '../request'

export const getFeedbackTracking = () => {
  /**
 * @summary Lấy danh sách phản ánh với khả năng theo dõi xử lý
Có thể lọc theo trạng thái, tiêu đề, số điện thoại
 */
  const getApiZaloMiniAppAdminFeedbackTracking = (
    params?: GetApiZaloMiniAppAdminFeedbackTrackingParams
  ) => {
    return customRequest<PagedResultOfFeedbackTrackingDto>({
      url: `/api/zalo-mini-app/admin/feedback-tracking`,
      method: 'GET',
      params,
    })
  }
  /**
   * @summary Lấy chi tiết phản ánh theo dõi xử lý theo ID
   */
  const postApiZaloMiniAppAdminFeedbackTrackingPublicIdGet = (publicId: string) => {
    return customRequest<ApiResultOfFeedbackTrackingDto>({
      url: `/api/zalo-mini-app/admin/feedback-tracking/${publicId}/get`,
      method: 'POST',
    })
  }
  return {
    getApiZaloMiniAppAdminFeedbackTracking,
    postApiZaloMiniAppAdminFeedbackTrackingPublicIdGet,
  }
}
export type GetApiZaloMiniAppAdminFeedbackTrackingResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getFeedbackTracking>['getApiZaloMiniAppAdminFeedbackTracking']>
  >
>
export type PostApiZaloMiniAppAdminFeedbackTrackingPublicIdGetResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getFeedbackTracking>['postApiZaloMiniAppAdminFeedbackTrackingPublicIdGet']
    >
  >
>
