/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfFeedbackAdminDto,
  ApiResultOfFeedbackDetailMobileDto,
  ApiResultOfFeedbackStatusCountsDto,
  CreateFeedbackMobileDto,
  GetApiZaloMiniAppMobileFeedbackByStatusParams,
  GetApiZaloMiniAppMobileFeedbackHistoryParams,
  GetApiZaloMiniAppMobileFeedbackPublicIdByStatusParams,
  GetApiZaloMiniAppMobileFeedbackPublicIdParams,
  GetApiZaloMiniAppMobileFeedbackPublicParams,
  GetApiZaloMiniAppMobileFeedbackStatusCountsParams,
  PagedResultOfFeedbackMobileDto,
} from '../models'

import { customRequest } from '../request'

export const getFeedbackMobile = () => {
  /**
   * @summary Tạo phản ánh mới từ mobile app
   */
  const postApiZaloMiniAppMobileFeedbackCreate = (
    createFeedbackMobileDto: CreateFeedbackMobileDto
  ) => {
    return customRequest<ApiResultOfFeedbackAdminDto>({
      url: `/api/zalo-mini-app/mobile/feedback/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createFeedbackMobileDto,
    })
  }
  /**
   * @summary Lấy danh sách phản ánh công khai (có phân trang)
   */
  const getApiZaloMiniAppMobileFeedbackPublic = (
    params?: GetApiZaloMiniAppMobileFeedbackPublicParams
  ) => {
    return customRequest<PagedResultOfFeedbackMobileDto>({
      url: `/api/zalo-mini-app/mobile/feedback/public`,
      method: 'GET',
      params,
    })
  }
  /**
   * @summary Lấy lịch sử phản ánh của user theo số điện thoại
   */
  const getApiZaloMiniAppMobileFeedbackHistory = (
    params?: GetApiZaloMiniAppMobileFeedbackHistoryParams
  ) => {
    return customRequest<PagedResultOfFeedbackMobileDto>({
      url: `/api/zalo-mini-app/mobile/feedback/history`,
      method: 'GET',
      params,
    })
  }
  /**
   * @summary Lấy chi tiết phản ánh (công khai hoặc của user)
   */
  const getApiZaloMiniAppMobileFeedbackPublicId = (
    publicId: string,
    params?: GetApiZaloMiniAppMobileFeedbackPublicIdParams
  ) => {
    return customRequest<ApiResultOfFeedbackDetailMobileDto>({
      url: `/api/zalo-mini-app/mobile/feedback/${publicId}`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileFeedbackStatusCounts = (
    params?: GetApiZaloMiniAppMobileFeedbackStatusCountsParams
  ) => {
    return customRequest<ApiResultOfFeedbackStatusCountsDto>({
      url: `/api/zalo-mini-app/mobile/feedback/status-counts`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileFeedbackByStatus = (
    params?: GetApiZaloMiniAppMobileFeedbackByStatusParams
  ) => {
    return customRequest<PagedResultOfFeedbackMobileDto>({
      url: `/api/zalo-mini-app/mobile/feedback/by-status`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileFeedbackPublicIdByStatus = (
    publicId: string,
    params?: GetApiZaloMiniAppMobileFeedbackPublicIdByStatusParams
  ) => {
    return customRequest<ApiResultOfFeedbackDetailMobileDto>({
      url: `/api/zalo-mini-app/mobile/feedback/${publicId}/by-status`,
      method: 'GET',
      params,
    })
  }
  return {
    postApiZaloMiniAppMobileFeedbackCreate,
    getApiZaloMiniAppMobileFeedbackPublic,
    getApiZaloMiniAppMobileFeedbackHistory,
    getApiZaloMiniAppMobileFeedbackPublicId,
    getApiZaloMiniAppMobileFeedbackStatusCounts,
    getApiZaloMiniAppMobileFeedbackByStatus,
    getApiZaloMiniAppMobileFeedbackPublicIdByStatus,
  }
}
export type PostApiZaloMiniAppMobileFeedbackCreateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getFeedbackMobile>['postApiZaloMiniAppMobileFeedbackCreate']>
  >
>
export type GetApiZaloMiniAppMobileFeedbackPublicResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFeedbackMobile>['getApiZaloMiniAppMobileFeedbackPublic']>>
>
export type GetApiZaloMiniAppMobileFeedbackHistoryResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getFeedbackMobile>['getApiZaloMiniAppMobileFeedbackHistory']>
  >
>
export type GetApiZaloMiniAppMobileFeedbackPublicIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getFeedbackMobile>['getApiZaloMiniAppMobileFeedbackPublicId']>
  >
>
export type GetApiZaloMiniAppMobileFeedbackStatusCountsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getFeedbackMobile>['getApiZaloMiniAppMobileFeedbackStatusCounts']>
  >
>
export type GetApiZaloMiniAppMobileFeedbackByStatusResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getFeedbackMobile>['getApiZaloMiniAppMobileFeedbackByStatus']>
  >
>
export type GetApiZaloMiniAppMobileFeedbackPublicIdByStatusResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getFeedbackMobile>['getApiZaloMiniAppMobileFeedbackPublicIdByStatus']
    >
  >
>
