/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfFeedbackAdminDto,
  ApiResultOfFeedbackDetailDto,
  ApiResultOfFeedbackStatusDto,
  ApiResultOfListFeedbackStatusDto,
  CreateFeedbackDto,
  DeleteFeedbackCommand,
  GetApiZaloMiniAppAdminFeedbackListParams,
  GetApiZaloMiniAppAdminFeedbackStatusesParams,
  PagedResultOfFeedbackAdminDto,
  PagedResultOfFeedbackStatusDto,
  UpdateFeedbackDto,
} from '../models'

import { customRequest } from '../request'

export const getFeedbackAdmin = () => {
  /**
   * @summary Lấy danh sách phản ánh (có phân trang và filtering)
   */
  const getApiZaloMiniAppAdminFeedbackList = (
    params?: GetApiZaloMiniAppAdminFeedbackListParams
  ) => {
    return customRequest<PagedResultOfFeedbackAdminDto>({
      url: `/api/zalo-mini-app/admin/feedback/list`,
      method: 'GET',
      params,
    })
  }
  /**
   * @summary Lấy chi tiết phản ánh theo ID
   */
  const getApiZaloMiniAppAdminFeedbackPublicId = (publicId: string) => {
    return customRequest<ApiResultOfFeedbackDetailDto>({
      url: `/api/zalo-mini-app/admin/feedback/${publicId}`,
      method: 'GET',
    })
  }
  /**
   * @summary Tạo phản ánh mới (từ admin)
   */
  const postApiZaloMiniAppAdminFeedbackCreate = (createFeedbackDto: CreateFeedbackDto) => {
    return customRequest<ApiResultOfFeedbackAdminDto>({
      url: `/api/zalo-mini-app/admin/feedback/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createFeedbackDto,
    })
  }
  /**
   * @summary Cập nhật thông tin phản ánh
   */
  const postApiZaloMiniAppAdminFeedbackUpdate = (updateFeedbackDto: UpdateFeedbackDto) => {
    return customRequest<ApiResultOfFeedbackAdminDto>({
      url: `/api/zalo-mini-app/admin/feedback/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateFeedbackDto,
    })
  }
  /**
   * @summary Xóa phản ánh (soft delete)
   */
  const postApiZaloMiniAppAdminFeedbackDelete = (deleteFeedbackCommand: DeleteFeedbackCommand) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/feedback/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteFeedbackCommand,
    })
  }
  /**
   * @summary Lấy danh sách trạng thái phản ánh (có phân trang và filtering)
   */
  const getApiZaloMiniAppAdminFeedbackStatuses = (
    params?: GetApiZaloMiniAppAdminFeedbackStatusesParams
  ) => {
    return customRequest<PagedResultOfFeedbackStatusDto>({
      url: `/api/zalo-mini-app/admin/feedback/statuses`,
      method: 'GET',
      params,
    })
  }
  /**
   * @summary Lấy chi tiết trạng thái phản ánh theo ID
   */
  const getApiZaloMiniAppAdminFeedbackStatusesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfFeedbackStatusDto>({
      url: `/api/zalo-mini-app/admin/feedback/statuses/${publicId}`,
      method: 'GET',
    })
  }
  /**
   * @summary Lấy danh sách trạng thái phản ánh đang hoạt động (dùng cho dropdown/selection)
   */
  const getApiZaloMiniAppAdminFeedbackStatusesActive = () => {
    return customRequest<ApiResultOfListFeedbackStatusDto>({
      url: `/api/zalo-mini-app/admin/feedback/statuses/active`,
      method: 'GET',
    })
  }
  return {
    getApiZaloMiniAppAdminFeedbackList,
    getApiZaloMiniAppAdminFeedbackPublicId,
    postApiZaloMiniAppAdminFeedbackCreate,
    postApiZaloMiniAppAdminFeedbackUpdate,
    postApiZaloMiniAppAdminFeedbackDelete,
    getApiZaloMiniAppAdminFeedbackStatuses,
    getApiZaloMiniAppAdminFeedbackStatusesPublicId,
    getApiZaloMiniAppAdminFeedbackStatusesActive,
  }
}
export type GetApiZaloMiniAppAdminFeedbackListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFeedbackAdmin>['getApiZaloMiniAppAdminFeedbackList']>>
>
export type GetApiZaloMiniAppAdminFeedbackPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFeedbackAdmin>['getApiZaloMiniAppAdminFeedbackPublicId']>>
>
export type PostApiZaloMiniAppAdminFeedbackCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFeedbackAdmin>['postApiZaloMiniAppAdminFeedbackCreate']>>
>
export type PostApiZaloMiniAppAdminFeedbackUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFeedbackAdmin>['postApiZaloMiniAppAdminFeedbackUpdate']>>
>
export type PostApiZaloMiniAppAdminFeedbackDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFeedbackAdmin>['postApiZaloMiniAppAdminFeedbackDelete']>>
>
export type GetApiZaloMiniAppAdminFeedbackStatusesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFeedbackAdmin>['getApiZaloMiniAppAdminFeedbackStatuses']>>
>
export type GetApiZaloMiniAppAdminFeedbackStatusesPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getFeedbackAdmin>['getApiZaloMiniAppAdminFeedbackStatusesPublicId']
    >
  >
>
export type GetApiZaloMiniAppAdminFeedbackStatusesActiveResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getFeedbackAdmin>['getApiZaloMiniAppAdminFeedbackStatusesActive']>
  >
>
