/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  AssignFeedbackDto,
  CreateFeedbackResponseDto,
  ProcessFeedbackDto,
  UpdateFeedbackResponseDto,
} from '../models'

import { customRequest } from '../request'

export const getFeedbackProcessing = () => {
  /**
   * @summary Điều phối phản ánh cho phòng ban
   */
  const postApiZaloMiniAppAdminFeedbackAssign = (assignFeedbackDto: AssignFeedbackDto) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/feedback/assign`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: assignFeedbackDto,
    })
  }
  /**
   * @summary Xử lý phản ánh (cập nhật trạng thái)
   */
  const postApiZaloMiniAppAdminFeedbackProcess = (processFeedbackDto: ProcessFeedbackDto) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/feedback/process`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: processFeedbackDto,
    })
  }
  /**
   * @summary Tạo phản hồi cho phản ánh
   */
  const postApiZaloMiniAppAdminFeedbackFeedbackPublicIdResponse = (
    feedbackPublicId: string,
    createFeedbackResponseDto: CreateFeedbackResponseDto
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/feedback/${feedbackPublicId}/response`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createFeedbackResponseDto,
    })
  }
  /**
   * @summary Cập nhật phản hồi
   */
  const postApiZaloMiniAppAdminFeedbackResponseResponseIdUpdate = (
    responseId: number,
    updateFeedbackResponseDto: UpdateFeedbackResponseDto
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/feedback/response/${responseId}/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateFeedbackResponseDto,
    })
  }
  return {
    postApiZaloMiniAppAdminFeedbackAssign,
    postApiZaloMiniAppAdminFeedbackProcess,
    postApiZaloMiniAppAdminFeedbackFeedbackPublicIdResponse,
    postApiZaloMiniAppAdminFeedbackResponseResponseIdUpdate,
  }
}
export type PostApiZaloMiniAppAdminFeedbackAssignResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getFeedbackProcessing>['postApiZaloMiniAppAdminFeedbackAssign']>
  >
>
export type PostApiZaloMiniAppAdminFeedbackProcessResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getFeedbackProcessing>['postApiZaloMiniAppAdminFeedbackProcess']>
  >
>
export type PostApiZaloMiniAppAdminFeedbackFeedbackPublicIdResponseResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getFeedbackProcessing
      >['postApiZaloMiniAppAdminFeedbackFeedbackPublicIdResponse']
    >
  >
>
export type PostApiZaloMiniAppAdminFeedbackResponseResponseIdUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getFeedbackProcessing
      >['postApiZaloMiniAppAdminFeedbackResponseResponseIdUpdate']
    >
  >
>
