/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApproveFeedbackResponseDto,
  GetApiZaloMiniAppAdminFeedbackResponsesApprovedParams,
  GetApiZaloMiniAppAdminFeedbackResponsesPendingApprovalParams,
  PagedResultOfFeedbackResponseDto,
  RejectFeedbackResponseDto,
} from '../models'

import { customRequest } from '../request'

export const getFeedbackApproval = () => {
  /**
   * @summary Duyệt phản hồi của phòng ban
   */
  const postApiZaloMiniAppAdminFeedbackResponsesResponseIdApprove = (
    responseId: number,
    approveFeedbackResponseDto: ApproveFeedbackResponseDto
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/feedback/responses/${responseId}/approve`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: approveFeedbackResponseDto,
    })
  }
  /**
   * @summary Từ chối phản hồi của phòng ban
   */
  const postApiZaloMiniAppAdminFeedbackResponsesResponseIdReject = (
    responseId: number,
    rejectFeedbackResponseDto: RejectFeedbackResponseDto
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/feedback/responses/${responseId}/reject`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: rejectFeedbackResponseDto,
    })
  }
  /**
   * @summary Lấy danh sách phản hồi cần duyệt
   */
  const getApiZaloMiniAppAdminFeedbackResponsesPendingApproval = (
    params?: GetApiZaloMiniAppAdminFeedbackResponsesPendingApprovalParams
  ) => {
    return customRequest<PagedResultOfFeedbackResponseDto>({
      url: `/api/zalo-mini-app/admin/feedback/responses/pending-approval`,
      method: 'GET',
      params,
    })
  }
  /**
   * @summary Lấy danh sách phản hồi đã duyệt
   */
  const getApiZaloMiniAppAdminFeedbackResponsesApproved = (
    params?: GetApiZaloMiniAppAdminFeedbackResponsesApprovedParams
  ) => {
    return customRequest<PagedResultOfFeedbackResponseDto>({
      url: `/api/zalo-mini-app/admin/feedback/responses/approved`,
      method: 'GET',
      params,
    })
  }
  return {
    postApiZaloMiniAppAdminFeedbackResponsesResponseIdApprove,
    postApiZaloMiniAppAdminFeedbackResponsesResponseIdReject,
    getApiZaloMiniAppAdminFeedbackResponsesPendingApproval,
    getApiZaloMiniAppAdminFeedbackResponsesApproved,
  }
}
export type PostApiZaloMiniAppAdminFeedbackResponsesResponseIdApproveResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getFeedbackApproval
      >['postApiZaloMiniAppAdminFeedbackResponsesResponseIdApprove']
    >
  >
>
export type PostApiZaloMiniAppAdminFeedbackResponsesResponseIdRejectResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getFeedbackApproval
      >['postApiZaloMiniAppAdminFeedbackResponsesResponseIdReject']
    >
  >
>
export type GetApiZaloMiniAppAdminFeedbackResponsesPendingApprovalResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getFeedbackApproval
      >['getApiZaloMiniAppAdminFeedbackResponsesPendingApproval']
    >
  >
>
export type GetApiZaloMiniAppAdminFeedbackResponsesApprovedResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getFeedbackApproval>['getApiZaloMiniAppAdminFeedbackResponsesApproved']
    >
  >
>
