/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfListFileInfoDto,
  ApiResultOfListUploadFileResponseDto,
  GetApiFilesByEntityParams,
  PostApiFilesUploadBody,
} from '../models'

import { customRequest } from '../request'

export const getFiles = () => {
  const postApiFilesUpload = (postApiFilesUploadBody: PostApiFilesUploadBody) => {
    const formData = new FormData()
    if (postApiFilesUploadBody.files !== undefined) {
      postApiFilesUploadBody.files.forEach((value) => formData.append(`files`, value))
    }
    if (postApiFilesUploadBody.entityPublicId !== undefined) {
      formData.append(`entityPublicId`, postApiFilesUploadBody.entityPublicId)
    }
    if (postApiFilesUploadBody.entityId !== undefined) {
      formData.append(`entityId`, postApiFilesUploadBody.entityId.toString())
    }
    if (postApiFilesUploadBody.entityType !== undefined) {
      formData.append(`entityType`, postApiFilesUploadBody.entityType)
    }
    if (postApiFilesUploadBody.description !== undefined) {
      formData.append(`description`, postApiFilesUploadBody.description)
    }

    return customRequest<ApiResultOfListUploadFileResponseDto>({
      url: `/api/files/upload`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    })
  }
  const getApiFilesByEntity = (params?: GetApiFilesByEntityParams) => {
    return customRequest<ApiResultOfListFileInfoDto>({
      url: `/api/files/by-entity`,
      method: 'GET',
      params,
    })
  }
  const getApiFilesPublicId = (publicId: string) => {
    return customRequest<Blob>({
      url: `/api/files/${publicId}`,
      method: 'GET',
      responseType: 'blob',
    })
  }
  return { postApiFilesUpload, getApiFilesByEntity, getApiFilesPublicId }
}
export type PostApiFilesUploadResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFiles>['postApiFilesUpload']>>
>
export type GetApiFilesByEntityResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFiles>['getApiFilesByEntity']>>
>
export type GetApiFilesPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFiles>['getApiFilesPublicId']>>
>
