/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfBoolean,
  ApiResultOfHomestayDto,
  CreateHomestayCommand,
  DeleteHomestayCommand,
  GetApiZaloMiniAppAdminHomestaysParams,
  PagedResultOfHomestayDto,
  UpdateHomestayCommand,
} from '../models'

import { customRequest } from '../request'

export const getHomestaysAdmin = () => {
  const getApiZaloMiniAppAdminHomestays = (params?: GetApiZaloMiniAppAdminHomestaysParams) => {
    return customRequest<PagedResultOfHomestayDto>({
      url: `/api/zalo-mini-app/admin/homestays`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminHomestaysPublicId = (publicId: string) => {
    return customRequest<ApiResultOfHomestayDto>({
      url: `/api/zalo-mini-app/admin/homestays/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminHomestaysCreate = (createHomestayCommand: CreateHomestayCommand) => {
    return customRequest<ApiResultOfHomestayDto>({
      url: `/api/zalo-mini-app/admin/homestays/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createHomestayCommand,
    })
  }
  const postApiZaloMiniAppAdminHomestaysUpdate = (updateHomestayCommand: UpdateHomestayCommand) => {
    return customRequest<ApiResultOfHomestayDto>({
      url: `/api/zalo-mini-app/admin/homestays/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateHomestayCommand,
    })
  }
  const postApiZaloMiniAppAdminHomestaysDelete = (deleteHomestayCommand: DeleteHomestayCommand) => {
    return customRequest<ApiResultOfBoolean>({
      url: `/api/zalo-mini-app/admin/homestays/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteHomestayCommand,
    })
  }
  return {
    getApiZaloMiniAppAdminHomestays,
    getApiZaloMiniAppAdminHomestaysPublicId,
    postApiZaloMiniAppAdminHomestaysCreate,
    postApiZaloMiniAppAdminHomestaysUpdate,
    postApiZaloMiniAppAdminHomestaysDelete,
  }
}
export type GetApiZaloMiniAppAdminHomestaysResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getHomestaysAdmin>['getApiZaloMiniAppAdminHomestays']>>
>
export type GetApiZaloMiniAppAdminHomestaysPublicIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getHomestaysAdmin>['getApiZaloMiniAppAdminHomestaysPublicId']>
  >
>
export type PostApiZaloMiniAppAdminHomestaysCreateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getHomestaysAdmin>['postApiZaloMiniAppAdminHomestaysCreate']>
  >
>
export type PostApiZaloMiniAppAdminHomestaysUpdateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getHomestaysAdmin>['postApiZaloMiniAppAdminHomestaysUpdate']>
  >
>
export type PostApiZaloMiniAppAdminHomestaysDeleteResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getHomestaysAdmin>['postApiZaloMiniAppAdminHomestaysDelete']>
  >
>
