/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfHomestayMobileDto,
  GetApiZaloMiniAppMobileHomestaysParams,
  PagedResultOfHomestayMobileDto,
} from '../models'

import { customRequest } from '../request'

export const getHomestaysMobile = () => {
  const getApiZaloMiniAppMobileHomestays = (params?: GetApiZaloMiniAppMobileHomestaysParams) => {
    return customRequest<PagedResultOfHomestayMobileDto>({
      url: `/api/zalo-mini-app/mobile/homestays`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileHomestaysPublicId = (publicId: string) => {
    return customRequest<ApiResultOfHomestayMobileDto>({
      url: `/api/zalo-mini-app/mobile/homestays/${publicId}`,
      method: 'GET',
    })
  }
  return { getApiZaloMiniAppMobileHomestays, getApiZaloMiniAppMobileHomestaysPublicId }
}
export type GetApiZaloMiniAppMobileHomestaysResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getHomestaysMobile>['getApiZaloMiniAppMobileHomestays']>>
>
export type GetApiZaloMiniAppMobileHomestaysPublicIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getHomestaysMobile>['getApiZaloMiniAppMobileHomestaysPublicId']>
  >
>
