/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfHotlineCategoryDto,
  ApiResultOfHotlineDto,
  ApiResultOfListHotlineDto,
  CreateHotlineCategoryCommand,
  CreateHotlineCommand,
  DeleteHotlineCategoryCommand,
  DeleteHotlineCommand,
  GetApiZaloMiniAppAdminServicesHotlinesCategoriesParams,
  GetApiZaloMiniAppAdminServicesHotlinesParams,
  PagedResultOfHotlineCategoryDto,
  PagedResultOfHotlineDto,
  UpdateHotlineCategoryCommand,
  UpdateHotlineCommand,
} from '../models'

import { customRequest } from '../request'

export const getHotlinesAdmin = () => {
  const postApiZaloMiniAppAdminServicesHotlinesCategoriesCreate = (
    createHotlineCategoryCommand: CreateHotlineCategoryCommand
  ) => {
    return customRequest<ApiResultOfHotlineCategoryDto>({
      url: `/api/zalo-mini-app/admin/services/hotlines/categories/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createHotlineCategoryCommand,
    })
  }
  const getApiZaloMiniAppAdminServicesHotlinesCategories = (
    params?: GetApiZaloMiniAppAdminServicesHotlinesCategoriesParams
  ) => {
    return customRequest<PagedResultOfHotlineCategoryDto>({
      url: `/api/zalo-mini-app/admin/services/hotlines/categories`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminServicesHotlinesCategoriesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfHotlineCategoryDto>({
      url: `/api/zalo-mini-app/admin/services/hotlines/categories/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminServicesHotlinesCategoriesUpdate = (
    updateHotlineCategoryCommand: UpdateHotlineCategoryCommand
  ) => {
    return customRequest<ApiResultOfHotlineCategoryDto>({
      url: `/api/zalo-mini-app/admin/services/hotlines/categories/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateHotlineCategoryCommand,
    })
  }
  const postApiZaloMiniAppAdminServicesHotlinesCategoriesDelete = (
    deleteHotlineCategoryCommand: DeleteHotlineCategoryCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/services/hotlines/categories/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteHotlineCategoryCommand,
    })
  }
  const postApiZaloMiniAppAdminServicesHotlinesCreate = (
    createHotlineCommand: CreateHotlineCommand
  ) => {
    return customRequest<ApiResultOfHotlineDto>({
      url: `/api/zalo-mini-app/admin/services/hotlines/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createHotlineCommand,
    })
  }
  const getApiZaloMiniAppAdminServicesHotlines = (
    params?: GetApiZaloMiniAppAdminServicesHotlinesParams
  ) => {
    return customRequest<PagedResultOfHotlineDto>({
      url: `/api/zalo-mini-app/admin/services/hotlines`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminServicesHotlinesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfHotlineDto>({
      url: `/api/zalo-mini-app/admin/services/hotlines/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminServicesHotlinesUpdate = (
    updateHotlineCommand: UpdateHotlineCommand
  ) => {
    return customRequest<ApiResultOfHotlineDto>({
      url: `/api/zalo-mini-app/admin/services/hotlines/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateHotlineCommand,
    })
  }
  const postApiZaloMiniAppAdminServicesHotlinesDelete = (
    deleteHotlineCommand: DeleteHotlineCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/services/hotlines/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteHotlineCommand,
    })
  }
  const getApiZaloMiniAppAdminServicesHotlinesCategoriesCategoryPublicIdHotlines = (
    categoryPublicId: string
  ) => {
    return customRequest<ApiResultOfListHotlineDto>({
      url: `/api/zalo-mini-app/admin/services/hotlines/categories/${categoryPublicId}/hotlines`,
      method: 'GET',
    })
  }
  return {
    postApiZaloMiniAppAdminServicesHotlinesCategoriesCreate,
    getApiZaloMiniAppAdminServicesHotlinesCategories,
    getApiZaloMiniAppAdminServicesHotlinesCategoriesPublicId,
    postApiZaloMiniAppAdminServicesHotlinesCategoriesUpdate,
    postApiZaloMiniAppAdminServicesHotlinesCategoriesDelete,
    postApiZaloMiniAppAdminServicesHotlinesCreate,
    getApiZaloMiniAppAdminServicesHotlines,
    getApiZaloMiniAppAdminServicesHotlinesPublicId,
    postApiZaloMiniAppAdminServicesHotlinesUpdate,
    postApiZaloMiniAppAdminServicesHotlinesDelete,
    getApiZaloMiniAppAdminServicesHotlinesCategoriesCategoryPublicIdHotlines,
  }
}
export type PostApiZaloMiniAppAdminServicesHotlinesCategoriesCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getHotlinesAdmin>['postApiZaloMiniAppAdminServicesHotlinesCategoriesCreate']
    >
  >
>
export type GetApiZaloMiniAppAdminServicesHotlinesCategoriesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getHotlinesAdmin>['getApiZaloMiniAppAdminServicesHotlinesCategories']
    >
  >
>
export type GetApiZaloMiniAppAdminServicesHotlinesCategoriesPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getHotlinesAdmin
      >['getApiZaloMiniAppAdminServicesHotlinesCategoriesPublicId']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesHotlinesCategoriesUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getHotlinesAdmin>['postApiZaloMiniAppAdminServicesHotlinesCategoriesUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesHotlinesCategoriesDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getHotlinesAdmin>['postApiZaloMiniAppAdminServicesHotlinesCategoriesDelete']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesHotlinesCreateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getHotlinesAdmin>['postApiZaloMiniAppAdminServicesHotlinesCreate']>
  >
>
export type GetApiZaloMiniAppAdminServicesHotlinesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getHotlinesAdmin>['getApiZaloMiniAppAdminServicesHotlines']>>
>
export type GetApiZaloMiniAppAdminServicesHotlinesPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getHotlinesAdmin>['getApiZaloMiniAppAdminServicesHotlinesPublicId']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesHotlinesUpdateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getHotlinesAdmin>['postApiZaloMiniAppAdminServicesHotlinesUpdate']>
  >
>
export type PostApiZaloMiniAppAdminServicesHotlinesDeleteResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getHotlinesAdmin>['postApiZaloMiniAppAdminServicesHotlinesDelete']>
  >
>
export type GetApiZaloMiniAppAdminServicesHotlinesCategoriesCategoryPublicIdHotlinesResult =
  NonNullable<
    Awaited<
      ReturnType<
        ReturnType<
          typeof getHotlinesAdmin
        >['getApiZaloMiniAppAdminServicesHotlinesCategoriesCategoryPublicIdHotlines']
      >
    >
  >
