/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { ApiResultOfListHotlineCategoryMobileDto, ApiResultOfListHotlineDto } from '../models'

import { customRequest } from '../request'

export const getHotlinesMobile = () => {
  const getApiZaloMiniAppMobileServicesHotlinesAll = () => {
    return customRequest<ApiResultOfListHotlineCategoryMobileDto>({
      url: `/api/zalo-mini-app/mobile/services/hotlines/all`,
      method: 'GET',
    })
  }
  const getApiZaloMiniAppMobileServicesHotlinesCategoriesCategoryPublicIdHotlines = (
    categoryPublicId: string
  ) => {
    return customRequest<ApiResultOfListHotlineDto>({
      url: `/api/zalo-mini-app/mobile/services/hotlines/categories/${categoryPublicId}/hotlines`,
      method: 'GET',
    })
  }
  return {
    getApiZaloMiniAppMobileServicesHotlinesAll,
    getApiZaloMiniAppMobileServicesHotlinesCategoriesCategoryPublicIdHotlines,
  }
}
export type GetApiZaloMiniAppMobileServicesHotlinesAllResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getHotlinesMobile>['getApiZaloMiniAppMobileServicesHotlinesAll']>
  >
>
export type GetApiZaloMiniAppMobileServicesHotlinesCategoriesCategoryPublicIdHotlinesResult =
  NonNullable<
    Awaited<
      ReturnType<
        ReturnType<
          typeof getHotlinesMobile
        >['getApiZaloMiniAppMobileServicesHotlinesCategoriesCategoryPublicIdHotlines']
      >
    >
  >
