/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfIconCategoryDto,
  ApiResultOfIconDto,
  ApiResultOfIconGroupDto,
  ApiResultOfListEnumResult1,
  CreateIconCategoryCommand,
  CreateIconCommand,
  CreateIconGroupCommand,
  DeleteIconCategoryCommand,
  DeleteIconCommand,
  DeleteIconGroupCommand,
  GetApiZaloMiniAppAdminServicesIconCategoriesParams,
  GetApiZaloMiniAppAdminServicesIconGroupsParams,
  GetApiZaloMiniAppAdminServicesIconsParams,
  PagedResultOfIconCategoryDto,
  PagedResultOfIconDto,
  PagedResultOfIconGroupDto,
  UpdateIconCategoryCommand,
  UpdateIconCommand,
  UpdateIconGroupCommand,
} from '../models'

import { customRequest } from '../request'

export const getIconManagementAdmin = () => {
  const postApiZaloMiniAppAdminServicesIconCategoriesCreate = (
    createIconCategoryCommand: CreateIconCategoryCommand
  ) => {
    return customRequest<ApiResultOfIconCategoryDto>({
      url: `/api/zalo-mini-app/admin/services/icon-categories/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createIconCategoryCommand,
    })
  }
  const getApiZaloMiniAppAdminServicesIconCategories = (
    params?: GetApiZaloMiniAppAdminServicesIconCategoriesParams
  ) => {
    return customRequest<PagedResultOfIconCategoryDto>({
      url: `/api/zalo-mini-app/admin/services/icon-categories`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminServicesIconCategoriesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfIconCategoryDto>({
      url: `/api/zalo-mini-app/admin/services/icon-categories/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminServicesIconCategoriesUpdate = (
    updateIconCategoryCommand: UpdateIconCategoryCommand
  ) => {
    return customRequest<ApiResultOfIconCategoryDto>({
      url: `/api/zalo-mini-app/admin/services/icon-categories/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateIconCategoryCommand,
    })
  }
  const postApiZaloMiniAppAdminServicesIconCategoriesDelete = (
    deleteIconCategoryCommand: DeleteIconCategoryCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/services/icon-categories/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteIconCategoryCommand,
    })
  }
  const getApiZaloMiniAppAdminServicesIconCategoriesEnumAll = () => {
    return customRequest<ApiResultOfListEnumResult1>({
      url: `/api/zalo-mini-app/admin/services/icon-categories/enum/all`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminServicesIconGroupsCreate = (
    createIconGroupCommand: CreateIconGroupCommand
  ) => {
    return customRequest<ApiResultOfIconGroupDto>({
      url: `/api/zalo-mini-app/admin/services/icon-groups/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createIconGroupCommand,
    })
  }
  const getApiZaloMiniAppAdminServicesIconGroups = (
    params?: GetApiZaloMiniAppAdminServicesIconGroupsParams
  ) => {
    return customRequest<PagedResultOfIconGroupDto>({
      url: `/api/zalo-mini-app/admin/services/icon-groups`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminServicesIconGroupsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfIconGroupDto>({
      url: `/api/zalo-mini-app/admin/services/icon-groups/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminServicesIconGroupsUpdate = (
    updateIconGroupCommand: UpdateIconGroupCommand
  ) => {
    return customRequest<ApiResultOfIconGroupDto>({
      url: `/api/zalo-mini-app/admin/services/icon-groups/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateIconGroupCommand,
    })
  }
  const postApiZaloMiniAppAdminServicesIconGroupsDelete = (
    deleteIconGroupCommand: DeleteIconGroupCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/services/icon-groups/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteIconGroupCommand,
    })
  }
  const getApiZaloMiniAppAdminServicesIconGroupsEnumAll = () => {
    return customRequest<ApiResultOfListEnumResult1>({
      url: `/api/zalo-mini-app/admin/services/icon-groups/enum/all`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminServicesIconsCreate = (createIconCommand: CreateIconCommand) => {
    return customRequest<ApiResultOfIconDto>({
      url: `/api/zalo-mini-app/admin/services/icons/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createIconCommand,
    })
  }
  const getApiZaloMiniAppAdminServicesIcons = (
    params?: GetApiZaloMiniAppAdminServicesIconsParams
  ) => {
    return customRequest<PagedResultOfIconDto>({
      url: `/api/zalo-mini-app/admin/services/icons`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminServicesIconsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfIconDto>({
      url: `/api/zalo-mini-app/admin/services/icons/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminServicesIconsUpdate = (updateIconCommand: UpdateIconCommand) => {
    return customRequest<ApiResultOfIconDto>({
      url: `/api/zalo-mini-app/admin/services/icons/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateIconCommand,
    })
  }
  const postApiZaloMiniAppAdminServicesIconsDelete = (deleteIconCommand: DeleteIconCommand) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/services/icons/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteIconCommand,
    })
  }
  return {
    postApiZaloMiniAppAdminServicesIconCategoriesCreate,
    getApiZaloMiniAppAdminServicesIconCategories,
    getApiZaloMiniAppAdminServicesIconCategoriesPublicId,
    postApiZaloMiniAppAdminServicesIconCategoriesUpdate,
    postApiZaloMiniAppAdminServicesIconCategoriesDelete,
    getApiZaloMiniAppAdminServicesIconCategoriesEnumAll,
    postApiZaloMiniAppAdminServicesIconGroupsCreate,
    getApiZaloMiniAppAdminServicesIconGroups,
    getApiZaloMiniAppAdminServicesIconGroupsPublicId,
    postApiZaloMiniAppAdminServicesIconGroupsUpdate,
    postApiZaloMiniAppAdminServicesIconGroupsDelete,
    getApiZaloMiniAppAdminServicesIconGroupsEnumAll,
    postApiZaloMiniAppAdminServicesIconsCreate,
    getApiZaloMiniAppAdminServicesIcons,
    getApiZaloMiniAppAdminServicesIconsPublicId,
    postApiZaloMiniAppAdminServicesIconsUpdate,
    postApiZaloMiniAppAdminServicesIconsDelete,
  }
}
export type PostApiZaloMiniAppAdminServicesIconCategoriesCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getIconManagementAdmin
      >['postApiZaloMiniAppAdminServicesIconCategoriesCreate']
    >
  >
>
export type GetApiZaloMiniAppAdminServicesIconCategoriesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementAdmin>['getApiZaloMiniAppAdminServicesIconCategories']
    >
  >
>
export type GetApiZaloMiniAppAdminServicesIconCategoriesPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getIconManagementAdmin
      >['getApiZaloMiniAppAdminServicesIconCategoriesPublicId']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesIconCategoriesUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getIconManagementAdmin
      >['postApiZaloMiniAppAdminServicesIconCategoriesUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesIconCategoriesDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getIconManagementAdmin
      >['postApiZaloMiniAppAdminServicesIconCategoriesDelete']
    >
  >
>
export type GetApiZaloMiniAppAdminServicesIconCategoriesEnumAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getIconManagementAdmin
      >['getApiZaloMiniAppAdminServicesIconCategoriesEnumAll']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesIconGroupsCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementAdmin>['postApiZaloMiniAppAdminServicesIconGroupsCreate']
    >
  >
>
export type GetApiZaloMiniAppAdminServicesIconGroupsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementAdmin>['getApiZaloMiniAppAdminServicesIconGroups']
    >
  >
>
export type GetApiZaloMiniAppAdminServicesIconGroupsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementAdmin>['getApiZaloMiniAppAdminServicesIconGroupsPublicId']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesIconGroupsUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementAdmin>['postApiZaloMiniAppAdminServicesIconGroupsUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesIconGroupsDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementAdmin>['postApiZaloMiniAppAdminServicesIconGroupsDelete']
    >
  >
>
export type GetApiZaloMiniAppAdminServicesIconGroupsEnumAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementAdmin>['getApiZaloMiniAppAdminServicesIconGroupsEnumAll']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesIconsCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementAdmin>['postApiZaloMiniAppAdminServicesIconsCreate']
    >
  >
>
export type GetApiZaloMiniAppAdminServicesIconsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getIconManagementAdmin>['getApiZaloMiniAppAdminServicesIcons']>
  >
>
export type GetApiZaloMiniAppAdminServicesIconsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementAdmin>['getApiZaloMiniAppAdminServicesIconsPublicId']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesIconsUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementAdmin>['postApiZaloMiniAppAdminServicesIconsUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesIconsDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementAdmin>['postApiZaloMiniAppAdminServicesIconsDelete']
    >
  >
>
