/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfIconConfigDto,
  ApiResultOfListIconMobileDto,
  GetApiZaloMiniAppMobileServicesIconsIosRedirectParams,
} from '../models'

import { customRequest } from '../request'

export const getIconManagementMobile = () => {
  const getApiZaloMiniAppMobileServicesIconsIosRedirect = (
    params?: GetApiZaloMiniAppMobileServicesIconsIosRedirectParams
  ) => {
    return customRequest<null>({
      url: `/api/zalo-mini-app/mobile/services/icons/ios-redirect`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileServicesIconConfig = () => {
    return customRequest<ApiResultOfIconConfigDto>({
      url: `/api/zalo-mini-app/mobile/services/icon-config`,
      method: 'GET',
    })
  }
  const getApiZaloMiniAppMobileServicesIconsActive = () => {
    return customRequest<ApiResultOfListIconMobileDto>({
      url: `/api/zalo-mini-app/mobile/services/icons/active`,
      method: 'GET',
    })
  }
  return {
    getApiZaloMiniAppMobileServicesIconsIosRedirect,
    getApiZaloMiniAppMobileServicesIconConfig,
    getApiZaloMiniAppMobileServicesIconsActive,
  }
}
export type GetApiZaloMiniAppMobileServicesIconsIosRedirectResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementMobile>['getApiZaloMiniAppMobileServicesIconsIosRedirect']
    >
  >
>
export type GetApiZaloMiniAppMobileServicesIconConfigResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementMobile>['getApiZaloMiniAppMobileServicesIconConfig']
    >
  >
>
export type GetApiZaloMiniAppMobileServicesIconsActiveResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementMobile>['getApiZaloMiniAppMobileServicesIconsActive']
    >
  >
>
