/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfLoginResult,
  ApiResultOfString,
  ApiResultOfUserDto,
  ChangePasswordCommand,
  LoginQuery,
  RegisterCommand,
  ResetMyPasswordCommand,
} from '../models'

import { customRequest } from '../request'

export const getIdentity = () => {
  const postApiIdentityRegister = (registerCommand: RegisterCommand) => {
    return customRequest<ApiResultOfString>({
      url: `/api/identity/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerCommand,
    })
  }
  const postApiIdentityLogin = (loginQuery: LoginQuery) => {
    return customRequest<ApiResultOfLoginResult>({
      url: `/api/identity/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginQuery,
    })
  }
  const getApiIdentityCurrentUser = () => {
    return customRequest<ApiResultOfUserDto>({ url: `/api/identity/current-user`, method: 'GET' })
  }
  const postApiIdentityChangePassword = (changePasswordCommand: ChangePasswordCommand) => {
    return customRequest<ApiResult>({
      url: `/api/identity/change-password`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: changePasswordCommand,
    })
  }
  const postApiIdentityResetMyPassword = (resetMyPasswordCommand: ResetMyPasswordCommand) => {
    return customRequest<ApiResult>({
      url: `/api/identity/reset-my-password`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: resetMyPasswordCommand,
    })
  }
  return {
    postApiIdentityRegister,
    postApiIdentityLogin,
    getApiIdentityCurrentUser,
    postApiIdentityChangePassword,
    postApiIdentityResetMyPassword,
  }
}
export type PostApiIdentityRegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIdentity>['postApiIdentityRegister']>>
>
export type PostApiIdentityLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIdentity>['postApiIdentityLogin']>>
>
export type GetApiIdentityCurrentUserResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIdentity>['getApiIdentityCurrentUser']>>
>
export type PostApiIdentityChangePasswordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIdentity>['postApiIdentityChangePassword']>>
>
export type PostApiIdentityResetMyPasswordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIdentity>['postApiIdentityResetMyPassword']>>
>
