/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfListQuestionDto,
  ApiResultOfSurveyDetailDto,
  GetApiZaloMiniAppMobileKhaosatParams,
  GetApiZaloMiniAppMobileKhaosatQuestionsParams,
  GetApiZaloMiniAppMobileKhaosatTuluanParams,
  KhaoSatMobileControllerSubmitEssayRequest,
  PagedResultOfEssayQuestionDto,
  PagedResultOfSurveyDto,
  ResponseKhaoSatCommand,
} from '../models'

import { customRequest } from '../request'

export const getKhaoSatMobile = () => {
  const getApiZaloMiniAppMobileKhaosat = (params?: GetApiZaloMiniAppMobileKhaosatParams) => {
    return customRequest<PagedResultOfSurveyDto>({
      url: `/api/zalo-mini-app/mobile/khaosat`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileKhaosatId = (id: number) => {
    return customRequest<ApiResultOfSurveyDetailDto>({
      url: `/api/zalo-mini-app/mobile/khaosat/${id}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppMobileKhaosatResponses = (
    responseKhaoSatCommand: ResponseKhaoSatCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/mobile/khaosat/responses`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: responseKhaoSatCommand,
    })
  }
  const postApiZaloMiniAppMobileKhaosatResponsesEssay = (
    khaoSatMobileControllerSubmitEssayRequest: KhaoSatMobileControllerSubmitEssayRequest
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/mobile/khaosat/responses/essay`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: khaoSatMobileControllerSubmitEssayRequest,
    })
  }
  const getApiZaloMiniAppMobileKhaosatQuestions = (
    params?: GetApiZaloMiniAppMobileKhaosatQuestionsParams
  ) => {
    return customRequest<ApiResultOfListQuestionDto>({
      url: `/api/zalo-mini-app/mobile/khaosat/questions`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileKhaosatTuluan = (
    params?: GetApiZaloMiniAppMobileKhaosatTuluanParams
  ) => {
    return customRequest<PagedResultOfEssayQuestionDto>({
      url: `/api/zalo-mini-app/mobile/khaosat/tuluan`,
      method: 'GET',
      params,
    })
  }
  return {
    getApiZaloMiniAppMobileKhaosat,
    getApiZaloMiniAppMobileKhaosatId,
    postApiZaloMiniAppMobileKhaosatResponses,
    postApiZaloMiniAppMobileKhaosatResponsesEssay,
    getApiZaloMiniAppMobileKhaosatQuestions,
    getApiZaloMiniAppMobileKhaosatTuluan,
  }
}
export type GetApiZaloMiniAppMobileKhaosatResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKhaoSatMobile>['getApiZaloMiniAppMobileKhaosat']>>
>
export type GetApiZaloMiniAppMobileKhaosatIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKhaoSatMobile>['getApiZaloMiniAppMobileKhaosatId']>>
>
export type PostApiZaloMiniAppMobileKhaosatResponsesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getKhaoSatMobile>['postApiZaloMiniAppMobileKhaosatResponses']>
  >
>
export type PostApiZaloMiniAppMobileKhaosatResponsesEssayResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getKhaoSatMobile>['postApiZaloMiniAppMobileKhaosatResponsesEssay']>
  >
>
export type GetApiZaloMiniAppMobileKhaosatQuestionsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getKhaoSatMobile>['getApiZaloMiniAppMobileKhaosatQuestions']>
  >
>
export type GetApiZaloMiniAppMobileKhaosatTuluanResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKhaoSatMobile>['getApiZaloMiniAppMobileKhaosatTuluan']>>
>
