/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfProfileDto,
  ApiResultOfUserProfileDto,
  CreateProfileCommand,
  UpdateProfileCommand,
} from '../models'

import { customRequest } from '../request'

export const getProfile = () => {
  const getApiProfileMe = () => {
    return customRequest<ApiResultOfUserProfileDto>({ url: `/api/profile/me`, method: 'GET' })
  }
  const postApiProfileCreate = (createProfileCommand: CreateProfileCommand) => {
    return customRequest<ApiResultOfProfileDto>({
      url: `/api/profile/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createProfileCommand,
    })
  }
  const postApiProfileUpdate = (updateProfileCommand: UpdateProfileCommand) => {
    return customRequest<ApiResultOfProfileDto>({
      url: `/api/profile/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateProfileCommand,
    })
  }
  return { getApiProfileMe, postApiProfileCreate, postApiProfileUpdate }
}
export type GetApiProfileMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProfile>['getApiProfileMe']>>
>
export type PostApiProfileCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProfile>['postApiProfileCreate']>>
>
export type PostApiProfileUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProfile>['postApiProfileUpdate']>>
>
