/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { ApiResult, ApiResultOfUserProfileDto, DeleteProfileCommand } from '../models'

import { customRequest } from '../request'

export const getProfileAdmin = () => {
  const getApiAdminProfilesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfUserProfileDto>({
      url: `/api/admin/profiles/${publicId}`,
      method: 'GET',
    })
  }
  const postApiAdminProfilesDelete = (deleteProfileCommand: DeleteProfileCommand) => {
    return customRequest<ApiResult>({
      url: `/api/admin/profiles/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteProfileCommand,
    })
  }
  return { getApiAdminProfilesPublicId, postApiAdminProfilesDelete }
}
export type GetApiAdminProfilesPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProfileAdmin>['getApiAdminProfilesPublicId']>>
>
export type PostApiAdminProfilesDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProfileAdmin>['postApiAdminProfilesDelete']>>
>
