/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfSupportGroupCategoryDto,
  ApiResultOfSupportGroupDto,
  CreateSupportGroupCategoryCommand,
  CreateSupportGroupCommand,
  DeleteSupportGroupCategoryCommand,
  DeleteSupportGroupCommand,
  GetApiZaloMiniAppAdminServicesSupportGroupsCategoriesParams,
  GetApiZaloMiniAppAdminServicesSupportGroupsParams,
  PagedResultOfSupportGroupCategoryDto,
  PagedResultOfSupportGroupDto,
  UpdateSupportGroupCategoryCommand,
  UpdateSupportGroupCommand,
} from '../models'

import { customRequest } from '../request'

export const getSupportGroupsAdmin = () => {
  const postApiZaloMiniAppAdminServicesSupportGroupsCategoriesCreate = (
    createSupportGroupCategoryCommand: CreateSupportGroupCategoryCommand
  ) => {
    return customRequest<ApiResultOfSupportGroupCategoryDto>({
      url: `/api/zalo-mini-app/admin/services/support-groups/categories/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSupportGroupCategoryCommand,
    })
  }
  const getApiZaloMiniAppAdminServicesSupportGroupsCategories = (
    params?: GetApiZaloMiniAppAdminServicesSupportGroupsCategoriesParams
  ) => {
    return customRequest<PagedResultOfSupportGroupCategoryDto>({
      url: `/api/zalo-mini-app/admin/services/support-groups/categories`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminServicesSupportGroupsCategoriesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfSupportGroupCategoryDto>({
      url: `/api/zalo-mini-app/admin/services/support-groups/categories/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminServicesSupportGroupsCategoriesUpdate = (
    updateSupportGroupCategoryCommand: UpdateSupportGroupCategoryCommand
  ) => {
    return customRequest<ApiResultOfSupportGroupCategoryDto>({
      url: `/api/zalo-mini-app/admin/services/support-groups/categories/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateSupportGroupCategoryCommand,
    })
  }
  const postApiZaloMiniAppAdminServicesSupportGroupsCategoriesDelete = (
    deleteSupportGroupCategoryCommand: DeleteSupportGroupCategoryCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/services/support-groups/categories/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteSupportGroupCategoryCommand,
    })
  }
  const postApiZaloMiniAppAdminServicesSupportGroupsCreate = (
    createSupportGroupCommand: CreateSupportGroupCommand
  ) => {
    return customRequest<ApiResultOfSupportGroupDto>({
      url: `/api/zalo-mini-app/admin/services/support-groups/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSupportGroupCommand,
    })
  }
  const getApiZaloMiniAppAdminServicesSupportGroups = (
    params?: GetApiZaloMiniAppAdminServicesSupportGroupsParams
  ) => {
    return customRequest<PagedResultOfSupportGroupDto>({
      url: `/api/zalo-mini-app/admin/services/support-groups`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminServicesSupportGroupsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfSupportGroupDto>({
      url: `/api/zalo-mini-app/admin/services/support-groups/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminServicesSupportGroupsUpdate = (
    updateSupportGroupCommand: UpdateSupportGroupCommand
  ) => {
    return customRequest<ApiResultOfSupportGroupDto>({
      url: `/api/zalo-mini-app/admin/services/support-groups/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateSupportGroupCommand,
    })
  }
  const postApiZaloMiniAppAdminServicesSupportGroupsDelete = (
    deleteSupportGroupCommand: DeleteSupportGroupCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/services/support-groups/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteSupportGroupCommand,
    })
  }
  return {
    postApiZaloMiniAppAdminServicesSupportGroupsCategoriesCreate,
    getApiZaloMiniAppAdminServicesSupportGroupsCategories,
    getApiZaloMiniAppAdminServicesSupportGroupsCategoriesPublicId,
    postApiZaloMiniAppAdminServicesSupportGroupsCategoriesUpdate,
    postApiZaloMiniAppAdminServicesSupportGroupsCategoriesDelete,
    postApiZaloMiniAppAdminServicesSupportGroupsCreate,
    getApiZaloMiniAppAdminServicesSupportGroups,
    getApiZaloMiniAppAdminServicesSupportGroupsPublicId,
    postApiZaloMiniAppAdminServicesSupportGroupsUpdate,
    postApiZaloMiniAppAdminServicesSupportGroupsDelete,
  }
}
export type PostApiZaloMiniAppAdminServicesSupportGroupsCategoriesCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSupportGroupsAdmin
      >['postApiZaloMiniAppAdminServicesSupportGroupsCategoriesCreate']
    >
  >
>
export type GetApiZaloMiniAppAdminServicesSupportGroupsCategoriesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSupportGroupsAdmin
      >['getApiZaloMiniAppAdminServicesSupportGroupsCategories']
    >
  >
>
export type GetApiZaloMiniAppAdminServicesSupportGroupsCategoriesPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSupportGroupsAdmin
      >['getApiZaloMiniAppAdminServicesSupportGroupsCategoriesPublicId']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesSupportGroupsCategoriesUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSupportGroupsAdmin
      >['postApiZaloMiniAppAdminServicesSupportGroupsCategoriesUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesSupportGroupsCategoriesDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSupportGroupsAdmin
      >['postApiZaloMiniAppAdminServicesSupportGroupsCategoriesDelete']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesSupportGroupsCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSupportGroupsAdmin>['postApiZaloMiniAppAdminServicesSupportGroupsCreate']
    >
  >
>
export type GetApiZaloMiniAppAdminServicesSupportGroupsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSupportGroupsAdmin>['getApiZaloMiniAppAdminServicesSupportGroups']
    >
  >
>
export type GetApiZaloMiniAppAdminServicesSupportGroupsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSupportGroupsAdmin
      >['getApiZaloMiniAppAdminServicesSupportGroupsPublicId']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesSupportGroupsUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSupportGroupsAdmin>['postApiZaloMiniAppAdminServicesSupportGroupsUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminServicesSupportGroupsDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSupportGroupsAdmin>['postApiZaloMiniAppAdminServicesSupportGroupsDelete']
    >
  >
>
