/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfSupportGroupCategoryDto,
  ApiResultOfSupportGroupMobileDto,
  GetApiZaloMiniAppMobileServicesSupportGroupsCategoriesParams,
  GetApiZaloMiniAppMobileServicesSupportGroupsParams,
  PagedResultOfSupportGroupCategoryDto,
  PagedResultOfSupportGroupMobileDto,
} from '../models'

import { customRequest } from '../request'

export const getSupportGroupsMobile = () => {
  const getApiZaloMiniAppMobileServicesSupportGroupsCategories = (
    params?: GetApiZaloMiniAppMobileServicesSupportGroupsCategoriesParams
  ) => {
    return customRequest<PagedResultOfSupportGroupCategoryDto>({
      url: `/api/zalo-mini-app/mobile/services/support-groups/categories`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileServicesSupportGroupsCategoriesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfSupportGroupCategoryDto>({
      url: `/api/zalo-mini-app/mobile/services/support-groups/categories/${publicId}`,
      method: 'GET',
    })
  }
  const getApiZaloMiniAppMobileServicesSupportGroups = (
    params?: GetApiZaloMiniAppMobileServicesSupportGroupsParams
  ) => {
    return customRequest<PagedResultOfSupportGroupMobileDto>({
      url: `/api/zalo-mini-app/mobile/services/support-groups`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileServicesSupportGroupsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfSupportGroupMobileDto>({
      url: `/api/zalo-mini-app/mobile/services/support-groups/${publicId}`,
      method: 'GET',
    })
  }
  return {
    getApiZaloMiniAppMobileServicesSupportGroupsCategories,
    getApiZaloMiniAppMobileServicesSupportGroupsCategoriesPublicId,
    getApiZaloMiniAppMobileServicesSupportGroups,
    getApiZaloMiniAppMobileServicesSupportGroupsPublicId,
  }
}
export type GetApiZaloMiniAppMobileServicesSupportGroupsCategoriesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSupportGroupsMobile
      >['getApiZaloMiniAppMobileServicesSupportGroupsCategories']
    >
  >
>
export type GetApiZaloMiniAppMobileServicesSupportGroupsCategoriesPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSupportGroupsMobile
      >['getApiZaloMiniAppMobileServicesSupportGroupsCategoriesPublicId']
    >
  >
>
export type GetApiZaloMiniAppMobileServicesSupportGroupsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSupportGroupsMobile>['getApiZaloMiniAppMobileServicesSupportGroups']
    >
  >
>
export type GetApiZaloMiniAppMobileServicesSupportGroupsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSupportGroupsMobile
      >['getApiZaloMiniAppMobileServicesSupportGroupsPublicId']
    >
  >
>
