/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfBoolean,
  ApiResultOfGuid,
  ApiResultOfTinTucArticleDetailDto,
  ApiResultOfTinTucCategoryDto,
  GetApiAdminTintucCategoriesParams,
  GetApiAdminTintucParams,
  PagedResultOfTinTucArticleDto,
  PagedResultOfTinTucCategoryDto,
  TinTucCreateArticleCommand,
  TinTucCreateCategoryCommand,
  TinTucUpdateArticleCommand,
  TinTucUpdateCategoryCommand,
  TinTucWorkflowArticleCommand,
} from '../models'

import { customRequest } from '../request'

export const getTinTucAdmin = () => {
  /**
   * @summary Lấy danh sách tin bài (phân trang, lọc)
   */
  const getApiAdminTintuc = (params?: GetApiAdminTintucParams) => {
    return customRequest<PagedResultOfTinTucArticleDto>({
      url: `/api/admin/tintuc`,
      method: 'GET',
      params,
    })
  }
  /**
   * @summary Tạo mới bản nháp tin bài
   */
  const postApiAdminTintuc = (tinTucCreateArticleCommand: TinTucCreateArticleCommand) => {
    return customRequest<ApiResultOfGuid>({
      url: `/api/admin/tintuc`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: tinTucCreateArticleCommand,
    })
  }
  /**
   * @summary Lấy chi tiết tin bài theo PublicId
   */
  const getApiAdminTintucPublicId = (publicId: string) => {
    return customRequest<ApiResultOfTinTucArticleDetailDto>({
      url: `/api/admin/tintuc/${publicId}`,
      method: 'GET',
    })
  }
  /**
   * @summary Cập nhật tin bài (khi đang ở bản nháp hoặc bị trả lại)
   */
  const putApiAdminTintucPublicId = (
    publicId: string,
    tinTucUpdateArticleCommand: TinTucUpdateArticleCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/admin/tintuc/${publicId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: tinTucUpdateArticleCommand,
    })
  }
  /**
   * @summary Xóa bài viết
   */
  const deleteApiAdminTintucPublicId = (publicId: string) => {
    return customRequest<ApiResult>({ url: `/api/admin/tintuc/${publicId}`, method: 'DELETE' })
  }
  /**
   * @summary Xử lý luồng bài viết (Gửi duyệt, Phê duyệt, Trả lại, Xuất bản, Thu hồi)
   */
  const postApiAdminTintucPublicIdWorkflow = (
    publicId: string,
    tinTucWorkflowArticleCommand: TinTucWorkflowArticleCommand
  ) => {
    return customRequest<ApiResultOfGuid>({
      url: `/api/admin/tintuc/${publicId}/workflow`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: tinTucWorkflowArticleCommand,
    })
  }
  const getApiAdminTintucCategories = (params?: GetApiAdminTintucCategoriesParams) => {
    return customRequest<PagedResultOfTinTucCategoryDto>({
      url: `/api/admin/tintuc/categories`,
      method: 'GET',
      params,
    })
  }
  const postApiAdminTintucCategories = (
    tinTucCreateCategoryCommand: TinTucCreateCategoryCommand
  ) => {
    return customRequest<ApiResultOfGuid>({
      url: `/api/admin/tintuc/categories`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: tinTucCreateCategoryCommand,
    })
  }
  const getApiAdminTintucCategoriesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfTinTucCategoryDto>({
      url: `/api/admin/tintuc/categories/${publicId}`,
      method: 'GET',
    })
  }
  const putApiAdminTintucCategoriesPublicId = (
    publicId: string,
    tinTucUpdateCategoryCommand: TinTucUpdateCategoryCommand
  ) => {
    return customRequest<ApiResultOfGuid>({
      url: `/api/admin/tintuc/categories/${publicId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: tinTucUpdateCategoryCommand,
    })
  }
  const deleteApiAdminTintucCategoriesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfBoolean>({
      url: `/api/admin/tintuc/categories/${publicId}`,
      method: 'DELETE',
    })
  }
  return {
    getApiAdminTintuc,
    postApiAdminTintuc,
    getApiAdminTintucPublicId,
    putApiAdminTintucPublicId,
    deleteApiAdminTintucPublicId,
    postApiAdminTintucPublicIdWorkflow,
    getApiAdminTintucCategories,
    postApiAdminTintucCategories,
    getApiAdminTintucCategoriesPublicId,
    putApiAdminTintucCategoriesPublicId,
    deleteApiAdminTintucCategoriesPublicId,
  }
}
export type GetApiAdminTintucResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTinTucAdmin>['getApiAdminTintuc']>>
>
export type PostApiAdminTintucResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTinTucAdmin>['postApiAdminTintuc']>>
>
export type GetApiAdminTintucPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTinTucAdmin>['getApiAdminTintucPublicId']>>
>
export type PutApiAdminTintucPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTinTucAdmin>['putApiAdminTintucPublicId']>>
>
export type DeleteApiAdminTintucPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTinTucAdmin>['deleteApiAdminTintucPublicId']>>
>
export type PostApiAdminTintucPublicIdWorkflowResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTinTucAdmin>['postApiAdminTintucPublicIdWorkflow']>>
>
export type GetApiAdminTintucCategoriesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTinTucAdmin>['getApiAdminTintucCategories']>>
>
export type PostApiAdminTintucCategoriesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTinTucAdmin>['postApiAdminTintucCategories']>>
>
export type GetApiAdminTintucCategoriesPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTinTucAdmin>['getApiAdminTintucCategoriesPublicId']>>
>
export type PutApiAdminTintucCategoriesPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTinTucAdmin>['putApiAdminTintucCategoriesPublicId']>>
>
export type DeleteApiAdminTintucCategoriesPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTinTucAdmin>['deleteApiAdminTintucCategoriesPublicId']>>
>
