/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfTotalUserDto,
  CreateTotalUserCommand,
  GetApiZaloMiniAppMobileUserTotalUsersParams,
  PagedResultOfTotalUserDto,
} from '../models'

import { customRequest } from '../request'

export const getUserMobile = () => {
  const postApiZaloMiniAppMobileUserTotalUsersCreate = (
    createTotalUserCommand: CreateTotalUserCommand
  ) => {
    return customRequest<ApiResultOfTotalUserDto>({
      url: `/api/zalo-mini-app/mobile/user/total-users/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTotalUserCommand,
    })
  }
  const getApiZaloMiniAppMobileUserTotalUsers = (
    params?: GetApiZaloMiniAppMobileUserTotalUsersParams
  ) => {
    return customRequest<PagedResultOfTotalUserDto>({
      url: `/api/zalo-mini-app/mobile/user/total-users`,
      method: 'GET',
      params,
    })
  }
  return { postApiZaloMiniAppMobileUserTotalUsersCreate, getApiZaloMiniAppMobileUserTotalUsers }
}
export type PostApiZaloMiniAppMobileUserTotalUsersCreateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getUserMobile>['postApiZaloMiniAppMobileUserTotalUsersCreate']>
  >
>
export type GetApiZaloMiniAppMobileUserTotalUsersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserMobile>['getApiZaloMiniAppMobileUserTotalUsers']>>
>
