/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfInt32,
  ApiResultOfRoleDto,
  ApiResultOfString,
  ApiResultOfUserDto,
  CreateRoleCommand,
  CreateUserCommand,
  DeleteRoleCommand,
  DeleteUserCommand,
  GetApiUsersParams,
  GetApiUsersRolesParams,
  PagedResultOfRoleDto,
  PagedResultOfUserWithRolesDto,
  ResetUserPasswordCommand,
  UpdateRoleCommand,
  UpdateUserCommand,
  UpdateUserRolesCommand,
} from '../models'

import { customRequest } from '../request'

export const getUsers = () => {
  const postApiUsersCreate = (createUserCommand: CreateUserCommand) => {
    return customRequest<ApiResultOfString>({
      url: `/api/users/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createUserCommand,
    })
  }
  const postApiUsersUpdate = (updateUserCommand: UpdateUserCommand) => {
    return customRequest<ApiResult>({
      url: `/api/users/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateUserCommand,
    })
  }
  const postApiUsersDelete = (deleteUserCommand: DeleteUserCommand) => {
    return customRequest<ApiResult>({
      url: `/api/users/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteUserCommand,
    })
  }
  const postApiUsersUpdateRoles = (updateUserRolesCommand: UpdateUserRolesCommand) => {
    return customRequest<ApiResult>({
      url: `/api/users/update-roles`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateUserRolesCommand,
    })
  }
  const getApiUsers = (params?: GetApiUsersParams) => {
    return customRequest<PagedResultOfUserWithRolesDto>({
      url: `/api/users`,
      method: 'GET',
      params,
    })
  }
  const postApiUsersRolesCreate = (createRoleCommand: CreateRoleCommand) => {
    return customRequest<ApiResultOfInt32>({
      url: `/api/users/roles/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createRoleCommand,
    })
  }
  const getApiUsersRoles = (params?: GetApiUsersRolesParams) => {
    return customRequest<PagedResultOfRoleDto>({ url: `/api/users/roles`, method: 'GET', params })
  }
  const getApiUsersRolesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfRoleDto>({ url: `/api/users/roles/${publicId}`, method: 'GET' })
  }
  const postApiUsersRolesUpdate = (updateRoleCommand: UpdateRoleCommand) => {
    return customRequest<ApiResult>({
      url: `/api/users/roles/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateRoleCommand,
    })
  }
  const postApiUsersRolesDelete = (deleteRoleCommand: DeleteRoleCommand) => {
    return customRequest<ApiResult>({
      url: `/api/users/roles/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteRoleCommand,
    })
  }
  const getApiUsersPublicId = (publicId: string) => {
    return customRequest<ApiResultOfUserDto>({ url: `/api/users/${publicId}`, method: 'GET' })
  }
  const postApiUsersResetPassword = (resetUserPasswordCommand: ResetUserPasswordCommand) => {
    return customRequest<ApiResult>({
      url: `/api/users/reset-password`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: resetUserPasswordCommand,
    })
  }
  return {
    postApiUsersCreate,
    postApiUsersUpdate,
    postApiUsersDelete,
    postApiUsersUpdateRoles,
    getApiUsers,
    postApiUsersRolesCreate,
    getApiUsersRoles,
    getApiUsersRolesPublicId,
    postApiUsersRolesUpdate,
    postApiUsersRolesDelete,
    getApiUsersPublicId,
    postApiUsersResetPassword,
  }
}
export type PostApiUsersCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postApiUsersCreate']>>
>
export type PostApiUsersUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postApiUsersUpdate']>>
>
export type PostApiUsersDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postApiUsersDelete']>>
>
export type PostApiUsersUpdateRolesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postApiUsersUpdateRoles']>>
>
export type GetApiUsersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['getApiUsers']>>
>
export type PostApiUsersRolesCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postApiUsersRolesCreate']>>
>
export type GetApiUsersRolesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['getApiUsersRoles']>>
>
export type GetApiUsersRolesPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['getApiUsersRolesPublicId']>>
>
export type PostApiUsersRolesUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postApiUsersRolesUpdate']>>
>
export type PostApiUsersRolesDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postApiUsersRolesDelete']>>
>
export type GetApiUsersPublicIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['getApiUsersPublicId']>>
>
export type PostApiUsersResetPasswordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postApiUsersResetPassword']>>
>
