/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfListEnumResult1,
  ApiResultOfOcopEnterpriseDto,
  CreateOcopEnterpriseCommand,
  DeleteOcopEnterpriseCommand,
  GetApiZaloMiniAppAdminOcopEnterprisesParams,
  PagedResultOfOcopEnterpriseDto,
  UpdateOcopEnterpriseCommand,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppOcopEnterprisesAdmin = () => {
  const getApiZaloMiniAppAdminOcopEnterprises = (
    params?: GetApiZaloMiniAppAdminOcopEnterprisesParams
  ) => {
    return customRequest<PagedResultOfOcopEnterpriseDto>({
      url: `/api/zalo-mini-app/admin/ocop-enterprises`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminOcopEnterprisesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfOcopEnterpriseDto>({
      url: `/api/zalo-mini-app/admin/ocop-enterprises/${publicId}`,
      method: 'GET',
    })
  }
  const getApiZaloMiniAppAdminOcopEnterprisesEnumAll = () => {
    return customRequest<ApiResultOfListEnumResult1>({
      url: `/api/zalo-mini-app/admin/ocop-enterprises/enum/all`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminOcopEnterprisesCreate = (
    createOcopEnterpriseCommand: CreateOcopEnterpriseCommand
  ) => {
    return customRequest<ApiResultOfOcopEnterpriseDto>({
      url: `/api/zalo-mini-app/admin/ocop-enterprises/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createOcopEnterpriseCommand,
    })
  }
  const postApiZaloMiniAppAdminOcopEnterprisesUpdate = (
    updateOcopEnterpriseCommand: UpdateOcopEnterpriseCommand
  ) => {
    return customRequest<ApiResultOfOcopEnterpriseDto>({
      url: `/api/zalo-mini-app/admin/ocop-enterprises/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateOcopEnterpriseCommand,
    })
  }
  const postApiZaloMiniAppAdminOcopEnterprisesDelete = (
    deleteOcopEnterpriseCommand: DeleteOcopEnterpriseCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/ocop-enterprises/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteOcopEnterpriseCommand,
    })
  }
  return {
    getApiZaloMiniAppAdminOcopEnterprises,
    getApiZaloMiniAppAdminOcopEnterprisesPublicId,
    getApiZaloMiniAppAdminOcopEnterprisesEnumAll,
    postApiZaloMiniAppAdminOcopEnterprisesCreate,
    postApiZaloMiniAppAdminOcopEnterprisesUpdate,
    postApiZaloMiniAppAdminOcopEnterprisesDelete,
  }
}
export type GetApiZaloMiniAppAdminOcopEnterprisesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppOcopEnterprisesAdmin>['getApiZaloMiniAppAdminOcopEnterprises']
    >
  >
>
export type GetApiZaloMiniAppAdminOcopEnterprisesPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopEnterprisesAdmin
      >['getApiZaloMiniAppAdminOcopEnterprisesPublicId']
    >
  >
>
export type GetApiZaloMiniAppAdminOcopEnterprisesEnumAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopEnterprisesAdmin
      >['getApiZaloMiniAppAdminOcopEnterprisesEnumAll']
    >
  >
>
export type PostApiZaloMiniAppAdminOcopEnterprisesCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopEnterprisesAdmin
      >['postApiZaloMiniAppAdminOcopEnterprisesCreate']
    >
  >
>
export type PostApiZaloMiniAppAdminOcopEnterprisesUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopEnterprisesAdmin
      >['postApiZaloMiniAppAdminOcopEnterprisesUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminOcopEnterprisesDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopEnterprisesAdmin
      >['postApiZaloMiniAppAdminOcopEnterprisesDelete']
    >
  >
>
