/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfListEnumResult1,
  ApiResultOfOcopProductCategoryDto,
  CreateOcopProductCategoryCommand,
  DeleteOcopProductCategoryCommand,
  GetApiZaloMiniAppAdminOcopCategoriesParams,
  PagedResultOfOcopProductCategoryDto,
  UpdateOcopProductCategoryCommand,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppOcopCategoriesAdmin = () => {
  const getApiZaloMiniAppAdminOcopCategories = (
    params?: GetApiZaloMiniAppAdminOcopCategoriesParams
  ) => {
    return customRequest<PagedResultOfOcopProductCategoryDto>({
      url: `/api/zalo-mini-app/admin/ocop-categories`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminOcopCategoriesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfOcopProductCategoryDto>({
      url: `/api/zalo-mini-app/admin/ocop-categories/${publicId}`,
      method: 'GET',
    })
  }
  const getApiZaloMiniAppAdminOcopCategoriesEnumAll = () => {
    return customRequest<ApiResultOfListEnumResult1>({
      url: `/api/zalo-mini-app/admin/ocop-categories/enum/all`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminOcopCategoriesCreate = (
    createOcopProductCategoryCommand: CreateOcopProductCategoryCommand
  ) => {
    return customRequest<ApiResultOfOcopProductCategoryDto>({
      url: `/api/zalo-mini-app/admin/ocop-categories/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createOcopProductCategoryCommand,
    })
  }
  const postApiZaloMiniAppAdminOcopCategoriesUpdate = (
    updateOcopProductCategoryCommand: UpdateOcopProductCategoryCommand
  ) => {
    return customRequest<ApiResultOfOcopProductCategoryDto>({
      url: `/api/zalo-mini-app/admin/ocop-categories/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateOcopProductCategoryCommand,
    })
  }
  const postApiZaloMiniAppAdminOcopCategoriesDelete = (
    deleteOcopProductCategoryCommand: DeleteOcopProductCategoryCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/ocop-categories/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteOcopProductCategoryCommand,
    })
  }
  return {
    getApiZaloMiniAppAdminOcopCategories,
    getApiZaloMiniAppAdminOcopCategoriesPublicId,
    getApiZaloMiniAppAdminOcopCategoriesEnumAll,
    postApiZaloMiniAppAdminOcopCategoriesCreate,
    postApiZaloMiniAppAdminOcopCategoriesUpdate,
    postApiZaloMiniAppAdminOcopCategoriesDelete,
  }
}
export type GetApiZaloMiniAppAdminOcopCategoriesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppOcopCategoriesAdmin>['getApiZaloMiniAppAdminOcopCategories']
    >
  >
>
export type GetApiZaloMiniAppAdminOcopCategoriesPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopCategoriesAdmin
      >['getApiZaloMiniAppAdminOcopCategoriesPublicId']
    >
  >
>
export type GetApiZaloMiniAppAdminOcopCategoriesEnumAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopCategoriesAdmin
      >['getApiZaloMiniAppAdminOcopCategoriesEnumAll']
    >
  >
>
export type PostApiZaloMiniAppAdminOcopCategoriesCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopCategoriesAdmin
      >['postApiZaloMiniAppAdminOcopCategoriesCreate']
    >
  >
>
export type PostApiZaloMiniAppAdminOcopCategoriesUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopCategoriesAdmin
      >['postApiZaloMiniAppAdminOcopCategoriesUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminOcopCategoriesDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopCategoriesAdmin
      >['postApiZaloMiniAppAdminOcopCategoriesDelete']
    >
  >
>
