/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfTicketDto,
  CreateTicketCommand,
  DeleteTicketCommand,
  GetApiZaloMiniAppAdminTicketsParams,
  PagedResultOfTicketDto,
  UpdateTicketCommand,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppTicketsAdmin = () => {
  const getApiZaloMiniAppAdminTickets = (params?: GetApiZaloMiniAppAdminTicketsParams) => {
    return customRequest<PagedResultOfTicketDto>({
      url: `/api/zalo-mini-app/admin/tickets`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminTicketsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfTicketDto>({
      url: `/api/zalo-mini-app/admin/tickets/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminTicketsCreate = (createTicketCommand: CreateTicketCommand) => {
    return customRequest<ApiResultOfTicketDto>({
      url: `/api/zalo-mini-app/admin/tickets/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTicketCommand,
    })
  }
  const postApiZaloMiniAppAdminTicketsUpdate = (updateTicketCommand: UpdateTicketCommand) => {
    return customRequest<ApiResultOfTicketDto>({
      url: `/api/zalo-mini-app/admin/tickets/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateTicketCommand,
    })
  }
  const postApiZaloMiniAppAdminTicketsDelete = (deleteTicketCommand: DeleteTicketCommand) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/tickets/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteTicketCommand,
    })
  }
  return {
    getApiZaloMiniAppAdminTickets,
    getApiZaloMiniAppAdminTicketsPublicId,
    postApiZaloMiniAppAdminTicketsCreate,
    postApiZaloMiniAppAdminTicketsUpdate,
    postApiZaloMiniAppAdminTicketsDelete,
  }
}
export type GetApiZaloMiniAppAdminTicketsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppTicketsAdmin>['getApiZaloMiniAppAdminTickets']>
  >
>
export type GetApiZaloMiniAppAdminTicketsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppTicketsAdmin>['getApiZaloMiniAppAdminTicketsPublicId']
    >
  >
>
export type PostApiZaloMiniAppAdminTicketsCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppTicketsAdmin>['postApiZaloMiniAppAdminTicketsCreate']
    >
  >
>
export type PostApiZaloMiniAppAdminTicketsUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppTicketsAdmin>['postApiZaloMiniAppAdminTicketsUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminTicketsDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppTicketsAdmin>['postApiZaloMiniAppAdminTicketsDelete']
    >
  >
>
