/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfPaymentTransactionDto,
  GetApiZaloMiniAppAdminTransactionsParams,
  PagedResultOfPaymentTransactionDto,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppTransactionsAdmin = () => {
  const getApiZaloMiniAppAdminTransactions = (
    params?: GetApiZaloMiniAppAdminTransactionsParams
  ) => {
    return customRequest<PagedResultOfPaymentTransactionDto>({
      url: `/api/zalo-mini-app/admin/transactions`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminTransactionsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfPaymentTransactionDto>({
      url: `/api/zalo-mini-app/admin/transactions/${publicId}`,
      method: 'GET',
    })
  }
  return { getApiZaloMiniAppAdminTransactions, getApiZaloMiniAppAdminTransactionsPublicId }
}
export type GetApiZaloMiniAppAdminTransactionsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppTransactionsAdmin>['getApiZaloMiniAppAdminTransactions']
    >
  >
>
export type GetApiZaloMiniAppAdminTransactionsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppTransactionsAdmin
      >['getApiZaloMiniAppAdminTransactionsPublicId']
    >
  >
>
