/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfTourDto,
  CreateTourCommand,
  DeleteTourCommand,
  GetApiZaloMiniAppAdminToursParams,
  PagedResultOfTourDto,
  UpdateTourCommand,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppToursAdmin = () => {
  const getApiZaloMiniAppAdminTours = (params?: GetApiZaloMiniAppAdminToursParams) => {
    return customRequest<PagedResultOfTourDto>({
      url: `/api/zalo-mini-app/admin/tours`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminToursPublicId = (publicId: string) => {
    return customRequest<ApiResultOfTourDto>({
      url: `/api/zalo-mini-app/admin/tours/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminToursCreate = (createTourCommand: CreateTourCommand) => {
    return customRequest<ApiResultOfTourDto>({
      url: `/api/zalo-mini-app/admin/tours/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTourCommand,
    })
  }
  const postApiZaloMiniAppAdminToursUpdate = (updateTourCommand: UpdateTourCommand) => {
    return customRequest<ApiResultOfTourDto>({
      url: `/api/zalo-mini-app/admin/tours/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateTourCommand,
    })
  }
  const postApiZaloMiniAppAdminToursDelete = (deleteTourCommand: DeleteTourCommand) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/tours/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteTourCommand,
    })
  }
  return {
    getApiZaloMiniAppAdminTours,
    getApiZaloMiniAppAdminToursPublicId,
    postApiZaloMiniAppAdminToursCreate,
    postApiZaloMiniAppAdminToursUpdate,
    postApiZaloMiniAppAdminToursDelete,
  }
}
export type GetApiZaloMiniAppAdminToursResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getZaloMiniAppToursAdmin>['getApiZaloMiniAppAdminTours']>>
>
export type GetApiZaloMiniAppAdminToursPublicIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppToursAdmin>['getApiZaloMiniAppAdminToursPublicId']>
  >
>
export type PostApiZaloMiniAppAdminToursCreateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppToursAdmin>['postApiZaloMiniAppAdminToursCreate']>
  >
>
export type PostApiZaloMiniAppAdminToursUpdateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppToursAdmin>['postApiZaloMiniAppAdminToursUpdate']>
  >
>
export type PostApiZaloMiniAppAdminToursDeleteResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppToursAdmin>['postApiZaloMiniAppAdminToursDelete']>
  >
>
