/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfBookingOrderDto,
  DeleteOrderCommand,
  GetApiZaloMiniAppAdminOrdersParams,
  PagedResultOfBookingOrderDto,
  UpdateOrderCommand,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppOrdersAdmin = () => {
  const getApiZaloMiniAppAdminOrders = (params?: GetApiZaloMiniAppAdminOrdersParams) => {
    return customRequest<PagedResultOfBookingOrderDto>({
      url: `/api/zalo-mini-app/admin/orders`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminOrdersPublicId = (publicId: string) => {
    return customRequest<ApiResultOfBookingOrderDto>({
      url: `/api/zalo-mini-app/admin/orders/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminOrdersUpdate = (updateOrderCommand: UpdateOrderCommand) => {
    return customRequest<ApiResultOfBookingOrderDto>({
      url: `/api/zalo-mini-app/admin/orders/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateOrderCommand,
    })
  }
  const postApiZaloMiniAppAdminOrdersDelete = (deleteOrderCommand: DeleteOrderCommand) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/orders/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteOrderCommand,
    })
  }
  return {
    getApiZaloMiniAppAdminOrders,
    getApiZaloMiniAppAdminOrdersPublicId,
    postApiZaloMiniAppAdminOrdersUpdate,
    postApiZaloMiniAppAdminOrdersDelete,
  }
}
export type GetApiZaloMiniAppAdminOrdersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getZaloMiniAppOrdersAdmin>['getApiZaloMiniAppAdminOrders']>>
>
export type GetApiZaloMiniAppAdminOrdersPublicIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppOrdersAdmin>['getApiZaloMiniAppAdminOrdersPublicId']>
  >
>
export type PostApiZaloMiniAppAdminOrdersUpdateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppOrdersAdmin>['postApiZaloMiniAppAdminOrdersUpdate']>
  >
>
export type PostApiZaloMiniAppAdminOrdersDeleteResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppOrdersAdmin>['postApiZaloMiniAppAdminOrdersDelete']>
  >
>
