/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfOcopProductDto,
  GetApiZaloMiniAppMobileOcopProductsByCategoryCategoryPublicIdParams,
  GetApiZaloMiniAppMobileOcopProductsByEnterpriseEnterprisePublicIdParams,
  PagedResultOfOcopProductDto,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppOcopProductsMobile = () => {
  const getApiZaloMiniAppMobileOcopProductsByCategoryCategoryPublicId = (
    categoryPublicId: string,
    params?: GetApiZaloMiniAppMobileOcopProductsByCategoryCategoryPublicIdParams
  ) => {
    return customRequest<PagedResultOfOcopProductDto>({
      url: `/api/zalo-mini-app/mobile/ocop-products/by-category/${categoryPublicId}`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileOcopProductsByEnterpriseEnterprisePublicId = (
    enterprisePublicId: string,
    params?: GetApiZaloMiniAppMobileOcopProductsByEnterpriseEnterprisePublicIdParams
  ) => {
    return customRequest<PagedResultOfOcopProductDto>({
      url: `/api/zalo-mini-app/mobile/ocop-products/by-enterprise/${enterprisePublicId}`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileOcopProductsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfOcopProductDto>({
      url: `/api/zalo-mini-app/mobile/ocop-products/${publicId}`,
      method: 'GET',
    })
  }
  return {
    getApiZaloMiniAppMobileOcopProductsByCategoryCategoryPublicId,
    getApiZaloMiniAppMobileOcopProductsByEnterpriseEnterprisePublicId,
    getApiZaloMiniAppMobileOcopProductsPublicId,
  }
}
export type GetApiZaloMiniAppMobileOcopProductsByCategoryCategoryPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopProductsMobile
      >['getApiZaloMiniAppMobileOcopProductsByCategoryCategoryPublicId']
    >
  >
>
export type GetApiZaloMiniAppMobileOcopProductsByEnterpriseEnterprisePublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopProductsMobile
      >['getApiZaloMiniAppMobileOcopProductsByEnterpriseEnterprisePublicId']
    >
  >
>
export type GetApiZaloMiniAppMobileOcopProductsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopProductsMobile
      >['getApiZaloMiniAppMobileOcopProductsPublicId']
    >
  >
>
