/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { ApiResultOfListOcopEnterpriseDto } from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppOcopEnterprisesMobile = () => {
  const getApiZaloMiniAppMobileOcopEnterprises = () => {
    return customRequest<ApiResultOfListOcopEnterpriseDto>({
      url: `/api/zalo-mini-app/mobile/ocop-enterprises`,
      method: 'GET',
    })
  }
  return { getApiZaloMiniAppMobileOcopEnterprises }
}
export type GetApiZaloMiniAppMobileOcopEnterprisesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopEnterprisesMobile
      >['getApiZaloMiniAppMobileOcopEnterprises']
    >
  >
>
