/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfGetPhoneNumberResponseDto,
  ApiResultOfTotalUserDto,
  CreateTotalUserCommand,
  DeleteTotalUserCommand,
  GetApiZaloMiniAppAdminUserTotalUsersParams,
  GetPhoneNumberRequestDto,
  PagedResultOfTotalUserDto,
  UpdateTotalUserCommand,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppUserAdmin = () => {
  /**
   * @summary Lấy thông tin số điện thoại của người dùng từ Zalo (Admin)
   */
  const postApiZaloMiniAppAdminUserGetPhoneNumber = (
    getPhoneNumberRequestDto: GetPhoneNumberRequestDto
  ) => {
    return customRequest<ApiResultOfGetPhoneNumberResponseDto>({
      url: `/api/zalo-mini-app/admin/user/get-phone-number`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: getPhoneNumberRequestDto,
    })
  }
  const postApiZaloMiniAppAdminUserTotalUsersCreate = (
    createTotalUserCommand: CreateTotalUserCommand
  ) => {
    return customRequest<ApiResultOfTotalUserDto>({
      url: `/api/zalo-mini-app/admin/user/total-users/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTotalUserCommand,
    })
  }
  const getApiZaloMiniAppAdminUserTotalUsers = (
    params?: GetApiZaloMiniAppAdminUserTotalUsersParams
  ) => {
    return customRequest<PagedResultOfTotalUserDto>({
      url: `/api/zalo-mini-app/admin/user/total-users`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminUserTotalUsersId = (id: number) => {
    return customRequest<ApiResultOfTotalUserDto>({
      url: `/api/zalo-mini-app/admin/user/total-users/${id}`,
      method: 'GET',
    })
  }
  const getApiZaloMiniAppAdminUserTotalUsersByUsernameUsername = (username: string) => {
    return customRequest<ApiResultOfTotalUserDto>({
      url: `/api/zalo-mini-app/admin/user/total-users/by-username/${username}`,
      method: 'GET',
    })
  }
  const getApiZaloMiniAppAdminUserTotalUsersByUserIdUserId = (userId: string) => {
    return customRequest<ApiResultOfTotalUserDto>({
      url: `/api/zalo-mini-app/admin/user/total-users/by-user-id/${userId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminUserTotalUsersUpdate = (
    updateTotalUserCommand: UpdateTotalUserCommand
  ) => {
    return customRequest<ApiResultOfTotalUserDto>({
      url: `/api/zalo-mini-app/admin/user/total-users/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateTotalUserCommand,
    })
  }
  const postApiZaloMiniAppAdminUserTotalUsersDelete = (
    deleteTotalUserCommand: DeleteTotalUserCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/user/total-users/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteTotalUserCommand,
    })
  }
  return {
    postApiZaloMiniAppAdminUserGetPhoneNumber,
    postApiZaloMiniAppAdminUserTotalUsersCreate,
    getApiZaloMiniAppAdminUserTotalUsers,
    getApiZaloMiniAppAdminUserTotalUsersId,
    getApiZaloMiniAppAdminUserTotalUsersByUsernameUsername,
    getApiZaloMiniAppAdminUserTotalUsersByUserIdUserId,
    postApiZaloMiniAppAdminUserTotalUsersUpdate,
    postApiZaloMiniAppAdminUserTotalUsersDelete,
  }
}
export type PostApiZaloMiniAppAdminUserGetPhoneNumberResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppUserAdmin>['postApiZaloMiniAppAdminUserGetPhoneNumber']
    >
  >
>
export type PostApiZaloMiniAppAdminUserTotalUsersCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppUserAdmin>['postApiZaloMiniAppAdminUserTotalUsersCreate']
    >
  >
>
export type GetApiZaloMiniAppAdminUserTotalUsersResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppUserAdmin>['getApiZaloMiniAppAdminUserTotalUsers']>
  >
>
export type GetApiZaloMiniAppAdminUserTotalUsersIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppUserAdmin>['getApiZaloMiniAppAdminUserTotalUsersId']>
  >
>
export type GetApiZaloMiniAppAdminUserTotalUsersByUsernameUsernameResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppUserAdmin
      >['getApiZaloMiniAppAdminUserTotalUsersByUsernameUsername']
    >
  >
>
export type GetApiZaloMiniAppAdminUserTotalUsersByUserIdUserIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppUserAdmin
      >['getApiZaloMiniAppAdminUserTotalUsersByUserIdUserId']
    >
  >
>
export type PostApiZaloMiniAppAdminUserTotalUsersUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppUserAdmin>['postApiZaloMiniAppAdminUserTotalUsersUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminUserTotalUsersDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppUserAdmin>['postApiZaloMiniAppAdminUserTotalUsersDelete']
    >
  >
>
