/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfHotelWithImagesDto,
  GetApiZaloMiniAppMobileHotelsParams,
  PagedResultOfHotelWithImagesDto,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppHotelsMobile = () => {
  const getApiZaloMiniAppMobileHotels = (params?: GetApiZaloMiniAppMobileHotelsParams) => {
    return customRequest<PagedResultOfHotelWithImagesDto>({
      url: `/api/zalo-mini-app/mobile/hotels`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileHotelsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfHotelWithImagesDto>({
      url: `/api/zalo-mini-app/mobile/hotels/${publicId}`,
      method: 'GET',
    })
  }
  return { getApiZaloMiniAppMobileHotels, getApiZaloMiniAppMobileHotelsPublicId }
}
export type GetApiZaloMiniAppMobileHotelsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppHotelsMobile>['getApiZaloMiniAppMobileHotels']>
  >
>
export type GetApiZaloMiniAppMobileHotelsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppHotelsMobile>['getApiZaloMiniAppMobileHotelsPublicId']
    >
  >
>
