/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfAnswerDto,
  ApiResultOfEssayQuestionDto,
  ApiResultOfListEssayResponseByUserDto,
  ApiResultOfObject,
  ApiResultOfOtherOpinionDto,
  ApiResultOfQuestionDto,
  ApiResultOfSurveyDetailDto,
  ApiResultOfSurveyDto,
  CheckResponseKhaoSatCommand,
  CreateEssayQuestionCommand,
  CreateSurveyCommand,
  DeleteAnswerCommand,
  DeleteEssayQuestionCommand,
  DeleteQuestionCommand,
  DeleteSurveyCommand,
  GetApiZaloMiniAppAdminKhaosatParams,
  GetApiZaloMiniAppAdminKhaosatResponsesUsersParams,
  GetApiZaloMiniAppAdminKhaosatThongkeChitietParams,
  GetApiZaloMiniAppAdminKhaosatTuluanParams,
  GetApiZaloMiniAppAdminKhaosatTuluanResponsesByUserParams,
  GetApiZaloMiniAppAdminKhaosatYkienkhacParams,
  InsertAnswerCommand,
  InsertOtherOpinionCommand,
  InsertQuestionCommand,
  PagedResultOfEssayQuestionDto,
  PagedResultOfInt64,
  PagedResultOfOtherOpinionDto,
  PagedResultOfSurveyDto,
  ResponseKhaoSatCommand,
  ThongKeKhaoSatQuery,
  UpdateAnswerCommand,
  UpdateEssayQuestionCommand,
  UpdateQuestionCommand,
  UpdateSurveyCommand,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppKhaoSatAdmin = () => {
  const getApiZaloMiniAppAdminKhaosat = (params?: GetApiZaloMiniAppAdminKhaosatParams) => {
    return customRequest<PagedResultOfSurveyDto>({
      url: `/api/zalo-mini-app/admin/khaosat`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminKhaosatId = (id: number) => {
    return customRequest<ApiResultOfSurveyDetailDto>({
      url: `/api/zalo-mini-app/admin/khaosat/${id}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminKhaosatCreate = (createSurveyCommand: CreateSurveyCommand) => {
    return customRequest<ApiResultOfSurveyDto>({
      url: `/api/zalo-mini-app/admin/khaosat/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSurveyCommand,
    })
  }
  const postApiZaloMiniAppAdminKhaosatUpdate = (updateSurveyCommand: UpdateSurveyCommand) => {
    return customRequest<ApiResultOfSurveyDto>({
      url: `/api/zalo-mini-app/admin/khaosat/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateSurveyCommand,
    })
  }
  const postApiZaloMiniAppAdminKhaosatDelete = (deleteSurveyCommand: DeleteSurveyCommand) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/khaosat/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteSurveyCommand,
    })
  }
  const postApiZaloMiniAppAdminKhaosatQuestionsCreate = (
    insertQuestionCommand: InsertQuestionCommand
  ) => {
    return customRequest<ApiResultOfQuestionDto>({
      url: `/api/zalo-mini-app/admin/khaosat/questions/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: insertQuestionCommand,
    })
  }
  const postApiZaloMiniAppAdminKhaosatQuestionsUpdate = (
    updateQuestionCommand: UpdateQuestionCommand
  ) => {
    return customRequest<ApiResultOfQuestionDto>({
      url: `/api/zalo-mini-app/admin/khaosat/questions/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateQuestionCommand,
    })
  }
  const postApiZaloMiniAppAdminKhaosatQuestionsDelete = (
    deleteQuestionCommand: DeleteQuestionCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/khaosat/questions/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteQuestionCommand,
    })
  }
  const postApiZaloMiniAppAdminKhaosatAnswersCreate = (
    insertAnswerCommand: InsertAnswerCommand
  ) => {
    return customRequest<ApiResultOfAnswerDto>({
      url: `/api/zalo-mini-app/admin/khaosat/answers/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: insertAnswerCommand,
    })
  }
  const getApiZaloMiniAppAdminKhaosatTuluan = (
    params?: GetApiZaloMiniAppAdminKhaosatTuluanParams
  ) => {
    return customRequest<PagedResultOfEssayQuestionDto>({
      url: `/api/zalo-mini-app/admin/khaosat/tuluan`,
      method: 'GET',
      params,
    })
  }
  const postApiZaloMiniAppAdminKhaosatTuluanCreate = (
    createEssayQuestionCommand: CreateEssayQuestionCommand
  ) => {
    return customRequest<ApiResultOfEssayQuestionDto>({
      url: `/api/zalo-mini-app/admin/khaosat/tuluan/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createEssayQuestionCommand,
    })
  }
  const postApiZaloMiniAppAdminKhaosatTuluanUpdate = (
    updateEssayQuestionCommand: UpdateEssayQuestionCommand
  ) => {
    return customRequest<ApiResultOfEssayQuestionDto>({
      url: `/api/zalo-mini-app/admin/khaosat/tuluan/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateEssayQuestionCommand,
    })
  }
  const postApiZaloMiniAppAdminKhaosatTuluanDelete = (
    deleteEssayQuestionCommand: DeleteEssayQuestionCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/khaosat/tuluan/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteEssayQuestionCommand,
    })
  }
  const postApiZaloMiniAppAdminKhaosatAnswersUpdate = (
    updateAnswerCommand: UpdateAnswerCommand
  ) => {
    return customRequest<ApiResultOfAnswerDto>({
      url: `/api/zalo-mini-app/admin/khaosat/answers/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateAnswerCommand,
    })
  }
  const postApiZaloMiniAppAdminKhaosatAnswersDelete = (
    deleteAnswerCommand: DeleteAnswerCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/khaosat/answers/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteAnswerCommand,
    })
  }
  const getApiZaloMiniAppAdminKhaosatYkienkhac = (
    params?: GetApiZaloMiniAppAdminKhaosatYkienkhacParams
  ) => {
    return customRequest<PagedResultOfOtherOpinionDto>({
      url: `/api/zalo-mini-app/admin/khaosat/ykienkhac`,
      method: 'GET',
      params,
    })
  }
  const postApiZaloMiniAppAdminKhaosatYkienkhacInsert = (
    insertOtherOpinionCommand: InsertOtherOpinionCommand
  ) => {
    return customRequest<ApiResultOfOtherOpinionDto>({
      url: `/api/zalo-mini-app/admin/khaosat/ykienkhac/insert`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: insertOtherOpinionCommand,
    })
  }
  const postApiZaloMiniAppAdminKhaosatResponsesCheck = (
    checkResponseKhaoSatCommand: CheckResponseKhaoSatCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/khaosat/responses/check`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: checkResponseKhaoSatCommand,
    })
  }
  const postApiZaloMiniAppAdminKhaosatResponses = (
    responseKhaoSatCommand: ResponseKhaoSatCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/khaosat/responses`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: responseKhaoSatCommand,
    })
  }
  const postApiZaloMiniAppAdminKhaosatThongke = (thongKeKhaoSatQuery: ThongKeKhaoSatQuery) => {
    return customRequest<ApiResultOfObject>({
      url: `/api/zalo-mini-app/admin/khaosat/thongke`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: thongKeKhaoSatQuery,
    })
  }
  const getApiZaloMiniAppAdminKhaosatResponsesUsers = (
    params?: GetApiZaloMiniAppAdminKhaosatResponsesUsersParams
  ) => {
    return customRequest<PagedResultOfInt64>({
      url: `/api/zalo-mini-app/admin/khaosat/responses/users`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminKhaosatThongkeChitiet = (
    params?: GetApiZaloMiniAppAdminKhaosatThongkeChitietParams
  ) => {
    return customRequest<ApiResultOfObject>({
      url: `/api/zalo-mini-app/admin/khaosat/thongke/chitiet`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminKhaosatTuluanResponsesByUser = (
    params?: GetApiZaloMiniAppAdminKhaosatTuluanResponsesByUserParams
  ) => {
    return customRequest<ApiResultOfListEssayResponseByUserDto>({
      url: `/api/zalo-mini-app/admin/khaosat/tuluan/responses/by-user`,
      method: 'GET',
      params,
    })
  }
  return {
    getApiZaloMiniAppAdminKhaosat,
    getApiZaloMiniAppAdminKhaosatId,
    postApiZaloMiniAppAdminKhaosatCreate,
    postApiZaloMiniAppAdminKhaosatUpdate,
    postApiZaloMiniAppAdminKhaosatDelete,
    postApiZaloMiniAppAdminKhaosatQuestionsCreate,
    postApiZaloMiniAppAdminKhaosatQuestionsUpdate,
    postApiZaloMiniAppAdminKhaosatQuestionsDelete,
    postApiZaloMiniAppAdminKhaosatAnswersCreate,
    getApiZaloMiniAppAdminKhaosatTuluan,
    postApiZaloMiniAppAdminKhaosatTuluanCreate,
    postApiZaloMiniAppAdminKhaosatTuluanUpdate,
    postApiZaloMiniAppAdminKhaosatTuluanDelete,
    postApiZaloMiniAppAdminKhaosatAnswersUpdate,
    postApiZaloMiniAppAdminKhaosatAnswersDelete,
    getApiZaloMiniAppAdminKhaosatYkienkhac,
    postApiZaloMiniAppAdminKhaosatYkienkhacInsert,
    postApiZaloMiniAppAdminKhaosatResponsesCheck,
    postApiZaloMiniAppAdminKhaosatResponses,
    postApiZaloMiniAppAdminKhaosatThongke,
    getApiZaloMiniAppAdminKhaosatResponsesUsers,
    getApiZaloMiniAppAdminKhaosatThongkeChitiet,
    getApiZaloMiniAppAdminKhaosatTuluanResponsesByUser,
  }
}
export type GetApiZaloMiniAppAdminKhaosatResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['getApiZaloMiniAppAdminKhaosat']>
  >
>
export type GetApiZaloMiniAppAdminKhaosatIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['getApiZaloMiniAppAdminKhaosatId']>
  >
>
export type PostApiZaloMiniAppAdminKhaosatCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatCreate']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatDelete']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatQuestionsCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatQuestionsCreate']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatQuestionsUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatQuestionsUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatQuestionsDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatQuestionsDelete']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatAnswersCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatAnswersCreate']
    >
  >
>
export type GetApiZaloMiniAppAdminKhaosatTuluanResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['getApiZaloMiniAppAdminKhaosatTuluan']>
  >
>
export type PostApiZaloMiniAppAdminKhaosatTuluanCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatTuluanCreate']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatTuluanUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatTuluanUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatTuluanDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatTuluanDelete']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatAnswersUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatAnswersUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatAnswersDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatAnswersDelete']
    >
  >
>
export type GetApiZaloMiniAppAdminKhaosatYkienkhacResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['getApiZaloMiniAppAdminKhaosatYkienkhac']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatYkienkhacInsertResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatYkienkhacInsert']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatResponsesCheckResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatResponsesCheck']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatResponsesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatResponses']
    >
  >
>
export type PostApiZaloMiniAppAdminKhaosatThongkeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['postApiZaloMiniAppAdminKhaosatThongke']
    >
  >
>
export type GetApiZaloMiniAppAdminKhaosatResponsesUsersResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['getApiZaloMiniAppAdminKhaosatResponsesUsers']
    >
  >
>
export type GetApiZaloMiniAppAdminKhaosatThongkeChitietResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppKhaoSatAdmin>['getApiZaloMiniAppAdminKhaosatThongkeChitiet']
    >
  >
>
export type GetApiZaloMiniAppAdminKhaosatTuluanResponsesByUserResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppKhaoSatAdmin
      >['getApiZaloMiniAppAdminKhaosatTuluanResponsesByUser']
    >
  >
>
