/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfDestinationDto,
  CreateDestinationCommand,
  DeleteDestinationCommand,
  GetApiZaloMiniAppAdminDestinationsParams,
  PagedResultOfDestinationDto,
  UpdateDestinationCommand,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppDestinationsAdmin = () => {
  const getApiZaloMiniAppAdminDestinations = (
    params?: GetApiZaloMiniAppAdminDestinationsParams
  ) => {
    return customRequest<PagedResultOfDestinationDto>({
      url: `/api/zalo-mini-app/admin/destinations`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminDestinationsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfDestinationDto>({
      url: `/api/zalo-mini-app/admin/destinations/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminDestinationsCreate = (
    createDestinationCommand: CreateDestinationCommand
  ) => {
    return customRequest<ApiResultOfDestinationDto>({
      url: `/api/zalo-mini-app/admin/destinations/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createDestinationCommand,
    })
  }
  const postApiZaloMiniAppAdminDestinationsUpdate = (
    updateDestinationCommand: UpdateDestinationCommand
  ) => {
    return customRequest<ApiResultOfDestinationDto>({
      url: `/api/zalo-mini-app/admin/destinations/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateDestinationCommand,
    })
  }
  const postApiZaloMiniAppAdminDestinationsDelete = (
    deleteDestinationCommand: DeleteDestinationCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/destinations/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteDestinationCommand,
    })
  }
  return {
    getApiZaloMiniAppAdminDestinations,
    getApiZaloMiniAppAdminDestinationsPublicId,
    postApiZaloMiniAppAdminDestinationsCreate,
    postApiZaloMiniAppAdminDestinationsUpdate,
    postApiZaloMiniAppAdminDestinationsDelete,
  }
}
export type GetApiZaloMiniAppAdminDestinationsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppDestinationsAdmin>['getApiZaloMiniAppAdminDestinations']
    >
  >
>
export type GetApiZaloMiniAppAdminDestinationsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppDestinationsAdmin
      >['getApiZaloMiniAppAdminDestinationsPublicId']
    >
  >
>
export type PostApiZaloMiniAppAdminDestinationsCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppDestinationsAdmin
      >['postApiZaloMiniAppAdminDestinationsCreate']
    >
  >
>
export type PostApiZaloMiniAppAdminDestinationsUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppDestinationsAdmin
      >['postApiZaloMiniAppAdminDestinationsUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminDestinationsDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppDestinationsAdmin
      >['postApiZaloMiniAppAdminDestinationsDelete']
    >
  >
>
