/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfArticleDto,
  GetApiZaloMiniAppMobileArticlesParams,
  PagedResultOfArticleDto,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppArticlesMobile = () => {
  const getApiZaloMiniAppMobileArticles = (params?: GetApiZaloMiniAppMobileArticlesParams) => {
    return customRequest<PagedResultOfArticleDto>({
      url: `/api/zalo-mini-app/mobile/articles`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileArticlesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfArticleDto>({
      url: `/api/zalo-mini-app/mobile/articles/${publicId}`,
      method: 'GET',
    })
  }
  return { getApiZaloMiniAppMobileArticles, getApiZaloMiniAppMobileArticlesPublicId }
}
export type GetApiZaloMiniAppMobileArticlesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppArticlesMobile>['getApiZaloMiniAppMobileArticles']>
  >
>
export type GetApiZaloMiniAppMobileArticlesPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppArticlesMobile>['getApiZaloMiniAppMobileArticlesPublicId']
    >
  >
>
