/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfDestinationDto,
  GetApiZaloMiniAppMobileDestinationsParams,
  PagedResultOfDestinationDto,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppDestinationsMobile = () => {
  const getApiZaloMiniAppMobileDestinations = (
    params?: GetApiZaloMiniAppMobileDestinationsParams
  ) => {
    return customRequest<PagedResultOfDestinationDto>({
      url: `/api/zalo-mini-app/mobile/destinations`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileDestinationsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfDestinationDto>({
      url: `/api/zalo-mini-app/mobile/destinations/${publicId}`,
      method: 'GET',
    })
  }
  return { getApiZaloMiniAppMobileDestinations, getApiZaloMiniAppMobileDestinationsPublicId }
}
export type GetApiZaloMiniAppMobileDestinationsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppDestinationsMobile>['getApiZaloMiniAppMobileDestinations']
    >
  >
>
export type GetApiZaloMiniAppMobileDestinationsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppDestinationsMobile
      >['getApiZaloMiniAppMobileDestinationsPublicId']
    >
  >
>
