/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfOcopProductDto,
  CreateOcopProductCommand,
  DeleteOcopProductCommand,
  GetApiZaloMiniAppAdminOcopProductsParams,
  PagedResultOfOcopProductDto,
  UpdateOcopProductCommand,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppOcopProductsAdmin = () => {
  const getApiZaloMiniAppAdminOcopProducts = (
    params?: GetApiZaloMiniAppAdminOcopProductsParams
  ) => {
    return customRequest<PagedResultOfOcopProductDto>({
      url: `/api/zalo-mini-app/admin/ocop-products`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminOcopProductsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfOcopProductDto>({
      url: `/api/zalo-mini-app/admin/ocop-products/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminOcopProductsCreate = (
    createOcopProductCommand: CreateOcopProductCommand
  ) => {
    return customRequest<ApiResultOfOcopProductDto>({
      url: `/api/zalo-mini-app/admin/ocop-products/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createOcopProductCommand,
    })
  }
  const postApiZaloMiniAppAdminOcopProductsUpdate = (
    updateOcopProductCommand: UpdateOcopProductCommand
  ) => {
    return customRequest<ApiResultOfOcopProductDto>({
      url: `/api/zalo-mini-app/admin/ocop-products/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateOcopProductCommand,
    })
  }
  const postApiZaloMiniAppAdminOcopProductsDelete = (
    deleteOcopProductCommand: DeleteOcopProductCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/ocop-products/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteOcopProductCommand,
    })
  }
  return {
    getApiZaloMiniAppAdminOcopProducts,
    getApiZaloMiniAppAdminOcopProductsPublicId,
    postApiZaloMiniAppAdminOcopProductsCreate,
    postApiZaloMiniAppAdminOcopProductsUpdate,
    postApiZaloMiniAppAdminOcopProductsDelete,
  }
}
export type GetApiZaloMiniAppAdminOcopProductsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppOcopProductsAdmin>['getApiZaloMiniAppAdminOcopProducts']
    >
  >
>
export type GetApiZaloMiniAppAdminOcopProductsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopProductsAdmin
      >['getApiZaloMiniAppAdminOcopProductsPublicId']
    >
  >
>
export type PostApiZaloMiniAppAdminOcopProductsCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopProductsAdmin
      >['postApiZaloMiniAppAdminOcopProductsCreate']
    >
  >
>
export type PostApiZaloMiniAppAdminOcopProductsUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopProductsAdmin
      >['postApiZaloMiniAppAdminOcopProductsUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminOcopProductsDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopProductsAdmin
      >['postApiZaloMiniAppAdminOcopProductsDelete']
    >
  >
>
