/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfRestaurantDto,
  GetApiZaloMiniAppMobileRestaurantsParams,
  PagedResultOfRestaurantDto,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppRestaurantsMobile = () => {
  const getApiZaloMiniAppMobileRestaurants = (
    params?: GetApiZaloMiniAppMobileRestaurantsParams
  ) => {
    return customRequest<PagedResultOfRestaurantDto>({
      url: `/api/zalo-mini-app/mobile/restaurants`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileRestaurantsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfRestaurantDto>({
      url: `/api/zalo-mini-app/mobile/restaurants/${publicId}`,
      method: 'GET',
    })
  }
  return { getApiZaloMiniAppMobileRestaurants, getApiZaloMiniAppMobileRestaurantsPublicId }
}
export type GetApiZaloMiniAppMobileRestaurantsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppRestaurantsMobile>['getApiZaloMiniAppMobileRestaurants']
    >
  >
>
export type GetApiZaloMiniAppMobileRestaurantsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppRestaurantsMobile
      >['getApiZaloMiniAppMobileRestaurantsPublicId']
    >
  >
>
