/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { ApiResultOfBookingOrderDto, CancelOrderCommand, CreateOrderCommand } from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppOrdersMobile = () => {
  const postApiZaloMiniAppMobileOrdersCreate = (createOrderCommand: CreateOrderCommand) => {
    return customRequest<ApiResultOfBookingOrderDto>({
      url: `/api/zalo-mini-app/mobile/orders/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createOrderCommand,
    })
  }
  const postApiZaloMiniAppMobileOrdersCancel = (cancelOrderCommand: CancelOrderCommand) => {
    return customRequest<ApiResultOfBookingOrderDto>({
      url: `/api/zalo-mini-app/mobile/orders/cancel`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: cancelOrderCommand,
    })
  }
  const getApiZaloMiniAppMobileOrdersPublicId = (publicId: string) => {
    return customRequest<ApiResultOfBookingOrderDto>({
      url: `/api/zalo-mini-app/mobile/orders/${publicId}`,
      method: 'GET',
    })
  }
  return {
    postApiZaloMiniAppMobileOrdersCreate,
    postApiZaloMiniAppMobileOrdersCancel,
    getApiZaloMiniAppMobileOrdersPublicId,
  }
}
export type PostApiZaloMiniAppMobileOrdersCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppOrdersMobile>['postApiZaloMiniAppMobileOrdersCreate']
    >
  >
>
export type PostApiZaloMiniAppMobileOrdersCancelResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppOrdersMobile>['postApiZaloMiniAppMobileOrdersCancel']
    >
  >
>
export type GetApiZaloMiniAppMobileOrdersPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppOrdersMobile>['getApiZaloMiniAppMobileOrdersPublicId']
    >
  >
>
