/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfTicketDto,
  GetApiZaloMiniAppMobileTicketsParams,
  PagedResultOfTicketDto,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppTicketsMobile = () => {
  const getApiZaloMiniAppMobileTickets = (params?: GetApiZaloMiniAppMobileTicketsParams) => {
    return customRequest<PagedResultOfTicketDto>({
      url: `/api/zalo-mini-app/mobile/tickets`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileTicketsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfTicketDto>({
      url: `/api/zalo-mini-app/mobile/tickets/${publicId}`,
      method: 'GET',
    })
  }
  return { getApiZaloMiniAppMobileTickets, getApiZaloMiniAppMobileTicketsPublicId }
}
export type GetApiZaloMiniAppMobileTicketsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppTicketsMobile>['getApiZaloMiniAppMobileTickets']>
  >
>
export type GetApiZaloMiniAppMobileTicketsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppTicketsMobile>['getApiZaloMiniAppMobileTicketsPublicId']
    >
  >
>
