/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfRestaurantDto,
  CreateRestaurantCommand,
  DeleteRestaurantCommand,
  GetApiZaloMiniAppAdminRestaurantsParams,
  PagedResultOfRestaurantDto,
  UpdateRestaurantCommand,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppRestaurantsAdmin = () => {
  const getApiZaloMiniAppAdminRestaurants = (params?: GetApiZaloMiniAppAdminRestaurantsParams) => {
    return customRequest<PagedResultOfRestaurantDto>({
      url: `/api/zalo-mini-app/admin/restaurants`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminRestaurantsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfRestaurantDto>({
      url: `/api/zalo-mini-app/admin/restaurants/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminRestaurantsCreate = (
    createRestaurantCommand: CreateRestaurantCommand
  ) => {
    return customRequest<ApiResultOfRestaurantDto>({
      url: `/api/zalo-mini-app/admin/restaurants/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createRestaurantCommand,
    })
  }
  const postApiZaloMiniAppAdminRestaurantsUpdate = (
    updateRestaurantCommand: UpdateRestaurantCommand
  ) => {
    return customRequest<ApiResultOfRestaurantDto>({
      url: `/api/zalo-mini-app/admin/restaurants/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateRestaurantCommand,
    })
  }
  const postApiZaloMiniAppAdminRestaurantsDelete = (
    deleteRestaurantCommand: DeleteRestaurantCommand
  ) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/restaurants/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteRestaurantCommand,
    })
  }
  return {
    getApiZaloMiniAppAdminRestaurants,
    getApiZaloMiniAppAdminRestaurantsPublicId,
    postApiZaloMiniAppAdminRestaurantsCreate,
    postApiZaloMiniAppAdminRestaurantsUpdate,
    postApiZaloMiniAppAdminRestaurantsDelete,
  }
}
export type GetApiZaloMiniAppAdminRestaurantsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppRestaurantsAdmin>['getApiZaloMiniAppAdminRestaurants']
    >
  >
>
export type GetApiZaloMiniAppAdminRestaurantsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppRestaurantsAdmin>['getApiZaloMiniAppAdminRestaurantsPublicId']
    >
  >
>
export type PostApiZaloMiniAppAdminRestaurantsCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppRestaurantsAdmin>['postApiZaloMiniAppAdminRestaurantsCreate']
    >
  >
>
export type PostApiZaloMiniAppAdminRestaurantsUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppRestaurantsAdmin>['postApiZaloMiniAppAdminRestaurantsUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminRestaurantsDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppRestaurantsAdmin>['postApiZaloMiniAppAdminRestaurantsDelete']
    >
  >
>
