/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfTourDto,
  GetApiZaloMiniAppMobileToursParams,
  PagedResultOfTourDto,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppToursMobile = () => {
  const getApiZaloMiniAppMobileTours = (params?: GetApiZaloMiniAppMobileToursParams) => {
    return customRequest<PagedResultOfTourDto>({
      url: `/api/zalo-mini-app/mobile/tours`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppMobileToursPublicId = (publicId: string) => {
    return customRequest<ApiResultOfTourDto>({
      url: `/api/zalo-mini-app/mobile/tours/${publicId}`,
      method: 'GET',
    })
  }
  return { getApiZaloMiniAppMobileTours, getApiZaloMiniAppMobileToursPublicId }
}
export type GetApiZaloMiniAppMobileToursResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getZaloMiniAppToursMobile>['getApiZaloMiniAppMobileTours']>>
>
export type GetApiZaloMiniAppMobileToursPublicIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppToursMobile>['getApiZaloMiniAppMobileToursPublicId']>
  >
>
