/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResultOfPaymentTransactionDto,
  CreateTransactionCommand,
  UpdateTransactionCommand,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppTransactionsMobile = () => {
  const postApiZaloMiniAppMobileTransactionsCreate = (
    createTransactionCommand: CreateTransactionCommand
  ) => {
    return customRequest<ApiResultOfPaymentTransactionDto>({
      url: `/api/zalo-mini-app/mobile/transactions/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTransactionCommand,
    })
  }
  const postApiZaloMiniAppMobileTransactionsWebhookUpdate = (
    updateTransactionCommand: UpdateTransactionCommand
  ) => {
    return customRequest<ApiResultOfPaymentTransactionDto>({
      url: `/api/zalo-mini-app/mobile/transactions/webhook/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateTransactionCommand,
    })
  }
  /**
 * @summary Endpoint được nhúng vào QR code — khi điện thoại quét sẽ mở URL này,
backend tự động xác nhận thanh toán và trả về trang HTML thông báo.
 */
  const getApiZaloMiniAppMobileTransactionsConfirmPublicId = (publicId: string) => {
    return customRequest<void>({
      url: `/api/zalo-mini-app/mobile/transactions/confirm/${publicId}`,
      method: 'GET',
    })
  }
  return {
    postApiZaloMiniAppMobileTransactionsCreate,
    postApiZaloMiniAppMobileTransactionsWebhookUpdate,
    getApiZaloMiniAppMobileTransactionsConfirmPublicId,
  }
}
export type PostApiZaloMiniAppMobileTransactionsCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppTransactionsMobile
      >['postApiZaloMiniAppMobileTransactionsCreate']
    >
  >
>
export type PostApiZaloMiniAppMobileTransactionsWebhookUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppTransactionsMobile
      >['postApiZaloMiniAppMobileTransactionsWebhookUpdate']
    >
  >
>
export type GetApiZaloMiniAppMobileTransactionsConfirmPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppTransactionsMobile
      >['getApiZaloMiniAppMobileTransactionsConfirmPublicId']
    >
  >
>
