/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfArticleDto,
  CreateArticleCommand,
  DeleteArticleCommand,
  GetApiZaloMiniAppAdminArticlesParams,
  PagedResultOfArticleDto,
  UpdateArticleCommand,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppArticlesAdmin = () => {
  const getApiZaloMiniAppAdminArticles = (params?: GetApiZaloMiniAppAdminArticlesParams) => {
    return customRequest<PagedResultOfArticleDto>({
      url: `/api/zalo-mini-app/admin/articles`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminArticlesPublicId = (publicId: string) => {
    return customRequest<ApiResultOfArticleDto>({
      url: `/api/zalo-mini-app/admin/articles/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminArticlesCreate = (createArticleCommand: CreateArticleCommand) => {
    return customRequest<ApiResultOfArticleDto>({
      url: `/api/zalo-mini-app/admin/articles/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createArticleCommand,
    })
  }
  const postApiZaloMiniAppAdminArticlesUpdate = (updateArticleCommand: UpdateArticleCommand) => {
    return customRequest<ApiResultOfArticleDto>({
      url: `/api/zalo-mini-app/admin/articles/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateArticleCommand,
    })
  }
  const postApiZaloMiniAppAdminArticlesDelete = (deleteArticleCommand: DeleteArticleCommand) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/articles/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteArticleCommand,
    })
  }
  return {
    getApiZaloMiniAppAdminArticles,
    getApiZaloMiniAppAdminArticlesPublicId,
    postApiZaloMiniAppAdminArticlesCreate,
    postApiZaloMiniAppAdminArticlesUpdate,
    postApiZaloMiniAppAdminArticlesDelete,
  }
}
export type GetApiZaloMiniAppAdminArticlesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppArticlesAdmin>['getApiZaloMiniAppAdminArticles']>
  >
>
export type GetApiZaloMiniAppAdminArticlesPublicIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppArticlesAdmin>['getApiZaloMiniAppAdminArticlesPublicId']
    >
  >
>
export type PostApiZaloMiniAppAdminArticlesCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppArticlesAdmin>['postApiZaloMiniAppAdminArticlesCreate']
    >
  >
>
export type PostApiZaloMiniAppAdminArticlesUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppArticlesAdmin>['postApiZaloMiniAppAdminArticlesUpdate']
    >
  >
>
export type PostApiZaloMiniAppAdminArticlesDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getZaloMiniAppArticlesAdmin>['postApiZaloMiniAppAdminArticlesDelete']
    >
  >
>
