/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResult,
  ApiResultOfHotelWithImagesDto,
  CreateHotelCommand,
  DeleteHotelCommand,
  GetApiZaloMiniAppAdminHotelsParams,
  PagedResultOfHotelWithImagesDto,
  UpdateHotelCommand,
} from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppHotelsAdmin = () => {
  const getApiZaloMiniAppAdminHotels = (params?: GetApiZaloMiniAppAdminHotelsParams) => {
    return customRequest<PagedResultOfHotelWithImagesDto>({
      url: `/api/zalo-mini-app/admin/hotels`,
      method: 'GET',
      params,
    })
  }
  const getApiZaloMiniAppAdminHotelsPublicId = (publicId: string) => {
    return customRequest<ApiResultOfHotelWithImagesDto>({
      url: `/api/zalo-mini-app/admin/hotels/${publicId}`,
      method: 'GET',
    })
  }
  const postApiZaloMiniAppAdminHotelsCreate = (createHotelCommand: CreateHotelCommand) => {
    return customRequest<ApiResultOfHotelWithImagesDto>({
      url: `/api/zalo-mini-app/admin/hotels/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createHotelCommand,
    })
  }
  const postApiZaloMiniAppAdminHotelsUpdate = (updateHotelCommand: UpdateHotelCommand) => {
    return customRequest<ApiResultOfHotelWithImagesDto>({
      url: `/api/zalo-mini-app/admin/hotels/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateHotelCommand,
    })
  }
  const postApiZaloMiniAppAdminHotelsDelete = (deleteHotelCommand: DeleteHotelCommand) => {
    return customRequest<ApiResult>({
      url: `/api/zalo-mini-app/admin/hotels/delete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteHotelCommand,
    })
  }
  return {
    getApiZaloMiniAppAdminHotels,
    getApiZaloMiniAppAdminHotelsPublicId,
    postApiZaloMiniAppAdminHotelsCreate,
    postApiZaloMiniAppAdminHotelsUpdate,
    postApiZaloMiniAppAdminHotelsDelete,
  }
}
export type GetApiZaloMiniAppAdminHotelsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getZaloMiniAppHotelsAdmin>['getApiZaloMiniAppAdminHotels']>>
>
export type GetApiZaloMiniAppAdminHotelsPublicIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppHotelsAdmin>['getApiZaloMiniAppAdminHotelsPublicId']>
  >
>
export type PostApiZaloMiniAppAdminHotelsCreateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppHotelsAdmin>['postApiZaloMiniAppAdminHotelsCreate']>
  >
>
export type PostApiZaloMiniAppAdminHotelsUpdateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppHotelsAdmin>['postApiZaloMiniAppAdminHotelsUpdate']>
  >
>
export type PostApiZaloMiniAppAdminHotelsDeleteResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getZaloMiniAppHotelsAdmin>['postApiZaloMiniAppAdminHotelsDelete']>
  >
>
