/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { ApiResultOfListOcopProductCategoryDto } from '../models'

import { customRequest } from '../request'

export const getZaloMiniAppOcopProductCategoriesMobile = () => {
  const getApiZaloMiniAppMobileOcopProductCategories = () => {
    return customRequest<ApiResultOfListOcopProductCategoryDto>({
      url: `/api/zalo-mini-app/mobile/ocop-product-categories`,
      method: 'GET',
    })
  }
  return { getApiZaloMiniAppMobileOcopProductCategories }
}
export type GetApiZaloMiniAppMobileOcopProductCategoriesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getZaloMiniAppOcopProductCategoriesMobile
      >['getApiZaloMiniAppMobileOcopProductCategories']
    >
  >
>
