export { default as DepartmentTable } from './components/DepartmentTable'
export { DepartmentForm } from './components/DepartmentForm'
export { DepartmentProfile } from './components/DepartmentProfile'
export { DepartmentListPage } from './pages/DepartmentListPage'
export { DepartmentCreatePage } from './pages/DepartmentCreatePage'
export { DepartmentDetailPage } from './pages/DepartmentDetailPage'
export { DepartmentEditPage } from './pages/DepartmentEditPage'
export { DepartmentUsersPage } from './pages/DepartmentUsersPage'
export { useDepartments, useCreateDepartment, useDeleteDepartment } from './hooks/useDepartments'
export { useDepartmentDetail } from './hooks/useDepartmentDetail'
