// Routes configuration - components are imported directly in AppRoutes.tsx to avoid circular dependencies
export const appRoutes = [
  {
    path: '/login',
    name: 'Đăng nhập',
    component: 'LoginPage',
    isProtected: false,
  },
  {
    path: '/dashboard',
    name: 'Trang chủ',
    component: 'DashboardPage',
    isProtected: true,
  },
  {
    path: '/users',
    name: 'Quản lý người dùng',
    component: 'UserListPage',
    isProtected: true,
  },
  {
    path: '/users/:id',
    name: 'Chi tiết người dùng',
    component: 'UserDetailPage',
    isProtected: true,
  },
  {
    path: '/users/create',
    name: 'Thêm người dùng',
    component: 'UserCreatePage',
    isProtected: true,
  },
  {
    path: '/users/:id/edit',
    name: 'Chỉnh sửa người dùng',
    component: 'UserEditPage',
    isProtected: true,
  },
  {
    path: '/organizations',
    name: 'Quản lý tổ chức',
    component: 'OrganizationListPage',
    isProtected: true,
  },
  {
    path: '/organizations/create',
    name: 'Thêm tổ chức',
    component: 'OrganizationCreatePage',
    isProtected: true,
  },
  {
    path: '/organizations/:id',
    name: 'Chi tiết tổ chức',
    component: 'OrganizationDetailPage',
    isProtected: true,
  },
  {
    path: '/departments',
    name: 'Quản lý phòng ban',
    component: 'DepartmentListPage',
    isProtected: true,
  },
  {
    path: '/departments/create',
    name: 'Thêm phòng ban',
    component: 'DepartmentCreatePage',
    isProtected: true,
  },
  {
    path: '/departments/:id',
    name: 'Chi tiết phòng ban',
    component: 'DepartmentDetailPage',
    isProtected: true,
  },
  {
    path: '/roles',
    name: 'Quản lý vai trò',
    component: 'RoleListPage',
    isProtected: true,
  },
  {
    path: '/roles/:id',
    name: 'Chi tiết vai trò',
    component: 'RoleDetailPage',
    isProtected: true,
  },
  {
    path: '/roles/create',
    name: 'Thêm vai trò',
    component: 'RoleCreatePage',
    isProtected: true,
  },
  {
    path: '/roles/:id/edit',
    name: 'Chỉnh sửa vai trò',
    component: 'RoleEditPage',
    isProtected: true,
  },
  {
    path: '/total-users',
    name: 'Thống kê người dùng',
    component: 'TotalUserListPage',
    isProtected: true,
  },
  {
    path: '/total-users/create',
    name: 'Thêm người dùng tổng hợp',
    component: 'TotalUserCreatePage',
    isProtected: true,
  },
  {
    path: '/total-users/:id',
    name: 'Chi tiết người dùng tổng hợp',
    component: 'TotalUserDetailPage',
    isProtected: true,
  },
  {
    path: '/total-users/:id/edit',
    name: 'Chỉnh sửa người dùng tổng hợp',
    component: 'TotalUserEditPage',
    isProtected: true,
  },
  {
    path: '/feedback',
    name: 'Điều phối phản ánh',
    component: 'FeedbackListPage',
    isProtected: true,
  },
  {
    path: '/feedback/create',
    name: 'Tạo phản ánh',
    component: 'FeedbackCreatePage',
    isProtected: true,
  },
  {
    path: '/feedback/processing',
    name: 'Xử lý phản ánh',
    component: 'FeedbackProcessingPage',
    isProtected: true,
  },
  {
    path: '/feedback/approval',
    name: 'Phê duyệt phản ánh',
    component: 'FeedbackApprovalPage',
    isProtected: true,
  },
  {
    path: '/feedback/public',
    name: 'Phản ánh hoàn thành',
    component: 'FeedbackPublicPage',
    isProtected: false,
  },
  {
    path: '/feedback/rejected',
    name: 'Phản ánh từ chối',
    component: 'FeedbackRejectedPage',
    isProtected: true,
  },
  // Specific detail routes for each feedback feature - MUST come before generic :publicId
  {
    path: '/feedback/public/:publicId',
    name: 'Chi tiết phản ánh hoàn thành',
    component: 'FeedbackDetailPage',
    isProtected: false,
  },
  {
    path: '/feedback/processing/:publicId',
    name: 'Chi tiết phản ánh xử lý',
    component: 'FeedbackDetailPage',
    isProtected: true,
  },
  {
    path: '/feedback/approval/:publicId',
    name: 'Chi tiết phản ánh phê duyệt',
    component: 'FeedbackDetailPage',
    isProtected: true,
  },
  {
    path: '/feedback/rejected/:publicId',
    name: 'Chi tiết phản ánh từ chối',
    component: 'FeedbackDetailPage',
    isProtected: true,
  },
  // Generic detail routes - fallback after specific ones
  {
    path: '/feedback/:publicId/edit',
    name: 'Chỉnh sửa phản ánh',
    component: 'FeedbackEditPage',
    isProtected: true,
  },
  {
    path: '/feedback/:publicId',
    name: 'Chi tiết phản ánh',
    component: 'FeedbackDetailPage',
    isProtected: true,
  },
  {
    path: '/support-groups',
    name: 'Quản lý nhóm hỗ trợ',
    component: 'SupportGroupListPage',
    isProtected: true,
  },
  {
    path: '/support-groups/create',
    name: 'Thêm nhóm hỗ trợ',
    component: 'SupportGroupCreatePage',
    isProtected: true,
  },
  {
    path: '/support-groups/:id',
    name: 'Chi tiết nhóm hỗ trợ',
    component: 'SupportGroupDetailPage',
    isProtected: true,
  },
  {
    path: '/support-groups/:id/edit',
    name: 'Chỉnh sửa nhóm hỗ trợ',
    component: 'SupportGroupEditPage',
    isProtected: true,
  },
  {
    path: '/khaosat',
    name: 'Quản lý khảo sát',
    component: 'KhaoSatListPage',
    isProtected: true,
  },
  {
    path: '/khaosat/create',
    name: 'Thêm khảo sát',
    component: 'KhaoSatCreatePage',
    isProtected: true,
  },
  {
    path: '/khaosat/:id',
    name: 'Chi tiết khảo sát',
    component: 'KhaoSatDetailPage',
    isProtected: true,
  },
  {
    path: '/khaosat/:id/edit',
    name: 'Chỉnh sửa khảo sát',
    component: 'KhaoSatEditPage',
    isProtected: true,
  },
] as const

export type AppRoute = typeof appRoutes[number]
